{{- if not .Values.secrets.s3.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helpers.s3SecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: {{ template "helpers.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  awsRegion: {{ .Values.secrets.s3.values.awsRegion | b64enc | quote }}
  awsAccessKeyId: {{ .Values.secrets.s3.values.awsAccessKeyId | b64enc | quote }}
  awsSecretAccessKey: {{ .Values.secrets.s3.values.awsSecretAccessKey | b64enc | quote }}
{{- end}}