//go:build !genrewrite

// code generated by genrewrite.go; DO NOT EDIT

package vm

import "github.com/SnellerInc/sneller/date"

func rewrite1(p *prog, v *value) (*value, bool) {
	switch v.op {
	case 4: /* mergemem */
		if len(v.args) == 1 {
			// (mergemem x) -> x
			if x := v.args[0]; true {
				return x, true
			}
		}
	case 8: /* and.k */
		if len(v.args) == 2 {
			// (and.k x (init)) -> x
			if x := v.args[0]; true {
				if _tmp12 := v.args[1]; _tmp12.op == 1 {
					return x, true
				}
			}
			// (and.k _ f:(false)) -> f
			if f := v.args[1]; f.op == 7 {
				return f, true
			}
			// (and.k f:(false) _) -> f
			if f := v.args[0]; f.op == 7 {
				return f, true
			}
			// (and.k x x) -> x
			if x := v.args[0]; true {
				if x == v.args[1] {
					return x, true
				}
			}
			// (and.k (init) x) -> x
			if _tmp13 := v.args[0]; _tmp13.op == 1 {
				if x := v.args[1]; true {
					return x, true
				}
			}
		}
	case 9: /* nand.k */
		if len(v.args) == 2 {
			// (nand.k x x) -> (false)
			if x := v.args[0]; true {
				if x == v.args[1] {
					return /* clobber v */ p.setssa(v, 7, nil), true
				}
			}
			// (nand.k (false) x) -> x
			if _tmp14 := v.args[0]; _tmp14.op == 7 {
				if x := v.args[1]; true {
					return x, true
				}
			}
			// (nand.k t:(init) _) -> (false)
			if t := v.args[0]; t.op == 1 {
				return /* clobber v */ p.setssa(v, 7, nil), true
			}
			// (nand.k _ f:(false)) -> f
			if f := v.args[1]; f.op == 7 {
				return f, true
			}
		}
	case 11: /* or.k */
		if len(v.args) == 2 {
			// (or.k _ t:(init)) -> t
			if t := v.args[1]; t.op == 1 {
				return t, true
			}
			// (or.k x x) -> x
			if x := v.args[0]; true {
				if x == v.args[1] {
					return x, true
				}
			}
			// (or.k x (false)) -> x
			if x := v.args[0]; true {
				if _tmp15 := v.args[1]; _tmp15.op == 7 {
					return x, true
				}
			}
			// (or.k (false) x) -> x
			if _tmp16 := v.args[0]; _tmp16.op == 7 {
				if x := v.args[1]; true {
					return x, true
				}
			}
			// (or.k t:(init) _) -> t
			if t := v.args[0]; t.op == 1 {
				return t, true
			}
		}
	case 12: /* xor.k */
		if len(v.args) == 2 {
			// (xor.k x (false)) -> x
			if x := v.args[0]; true {
				if _tmp17 := v.args[1]; _tmp17.op == 7 {
					return x, true
				}
			}
			// (xor.k t:(init) x) -> (nand.k x t)
			if t := v.args[0]; t.op == 1 {
				if x := v.args[1]; true {
					return /* clobber v */ p.setssa(v, 9, nil, x, t), true
				}
			}
			// (xor.k x t:(init)) -> (nand.k x t)
			if x := v.args[0]; true {
				if t := v.args[1]; t.op == 1 {
					return /* clobber v */ p.setssa(v, 9, nil, x, t), true
				}
			}
			// (xor.k (false) x) -> x
			if _tmp18 := v.args[0]; _tmp18.op == 7 {
				if x := v.args[1]; true {
					return x, true
				}
			}
			// (xor.k x x) -> (false)
			if x := v.args[0]; true {
				if x == v.args[1] {
					return /* clobber v */ p.setssa(v, 7, nil), true
				}
			}
		}
	case 13: /* xnor.k */
		if len(v.args) == 2 {
			// (xnor.k x x) -> (init)
			if x := v.args[0]; true {
				if x == v.args[1] {
					return p.values[0], true
				}
			}
			// (xnor.k f (init)) -> f
			if f := v.args[0]; true {
				if _tmp19 := v.args[1]; _tmp19.op == 1 {
					return f, true
				}
			}
			// (xnor.k (init) f) -> f
			if _tmp20 := v.args[0]; _tmp20.op == 1 {
				if f := v.args[1]; true {
					return f, true
				}
			}
			// (xnor.k f (false)) -> (nand.k f (init))
			if f := v.args[0]; true {
				if _tmp21 := v.args[1]; _tmp21.op == 7 {
					return /* clobber v */ p.setssa(v, 9, nil, f, p.values[0]), true
				}
			}
			// (xnor.k (false) f) -> (nand.k f (init))
			if _tmp22 := v.args[0]; _tmp22.op == 7 {
				if f := v.args[1]; true {
					return /* clobber v */ p.setssa(v, 9, nil, f, p.values[0]), true
				}
			}
		}
	case 38: /* cmpeq.f64 */
		if len(v.args) == 3 {
			// (cmpeq.f64 x x k) -> k
			if x := v.args[0]; true {
				if x == v.args[1] {
					if k := v.args[2]; true {
						return k, true
					}
				}
			}
		}
	case 40: /* cmpeq.i64 */
		if len(v.args) == 3 {
			// (cmpeq.i64 x x k) -> k
			if x := v.args[0]; true {
				if x == v.args[1] {
					if k := v.args[2]; true {
						return k, true
					}
				}
			}
		}
	case 50: /* cmple.f64 */
		if len(v.args) == 3 {
			// (cmple.f64 x x k) -> k
			if x := v.args[0]; true {
				if x == v.args[1] {
					if k := v.args[2]; true {
						return k, true
					}
				}
			}
		}
	case 52: /* cmple.i64 */
		if len(v.args) == 3 {
			// (cmple.i64 x x k) -> k
			if x := v.args[0]; true {
				if x == v.args[1] {
					if k := v.args[2]; true {
						return k, true
					}
				}
			}
		}
	case 54: /* cmpge.f64 */
		if len(v.args) == 3 {
			// (cmpge.f64 x x k) -> k
			if x := v.args[0]; true {
				if x == v.args[1] {
					if k := v.args[2]; true {
						return k, true
					}
				}
			}
		}
	case 56: /* cmpge.i64 */
		if len(v.args) == 3 {
			// (cmpge.i64 x x k) -> k
			if x := v.args[0]; true {
				if x == v.args[1] {
					if k := v.args[2]; true {
						return k, true
					}
				}
			}
		}
	case 73: /* cvt.k@i64 */
		if len(v.args) == 2 {
			// (cvt.k@i64 (init) _) -> (broadcast.i 1)
			if _tmp23 := v.args[0]; _tmp23.op == 1 {
				return /* clobber v */ p.setssa(v, 152, 1), true
			}
			// (cvt.k@i64 (false) _) -> (broadcast.i 0)
			if _tmp24 := v.args[0]; _tmp24.op == 7 {
				return /* clobber v */ p.setssa(v, 152, 0), true
			}
		}
	case 74: /* cvt.k@f64 */
		if len(v.args) == 2 {
			// (cvt.k@f64 (init) _) -> (broadcast.f 1)
			if _tmp25 := v.args[0]; _tmp25.op == 1 {
				return /* clobber v */ p.setssa(v, 151, 1), true
			}
			// (cvt.k@f64 (false) _) -> (broadcast.f 0)
			if _tmp26 := v.args[0]; _tmp26.op == 7 {
				return /* clobber v */ p.setssa(v, 151, 0), true
			}
		}
	case 75: /* cvt.i64@k */
		if len(v.args) == 2 {
			// (cvt.i64@k _tmp0:(broadcast.i imm) k) -> (and.k "p.choose(imm != 0)" k)
			if _tmp0 := v.args[0]; _tmp0.op == 152 {
				if k := v.args[1]; true {
					if imm := toi64(_tmp0.imm); true {
						return /* clobber v */ p.setssa(v, 8, nil, p.choose(imm != 0), k), true
					}
				}
			}
		}
	case 136: /* store.v */
		if len(v.args) == 3 {
			// (store.v mem ov k:(false) slot), "ov != k" -> (store.v mem k k slot)
			if mem := v.args[0]; true {
				if ov := v.args[1]; true {
					if k := v.args[2]; k.op == 7 {
						if slot := v.imm; true {
							if ov != k {
								return /* clobber v */ p.setssa(v, 136, slot, mem, k, k), true
							}
						}
					}
				}
			}
		}
	case 144: /* make.vk */
		if len(v.args) == 2 {
			// (make.vk val k), "p.mask(val) == k" -> val
			if val := v.args[0]; true {
				if k := v.args[1]; true {
					if p.mask(val) == k {
						return val, true
					}
				}
			}
		}
	case 145: /* floatk */
		if len(v.args) == 2 {
			// (floatk f k), "p.mask(f) == k" -> f
			if f := v.args[0]; true {
				if k := v.args[1]; true {
					if p.mask(f) == k {
						return f, true
					}
				}
			}
		}
	case 147: /* blend.v */
		if len(v.args) == 4 {
			// (blend.v _ (false) y k) -> (make.vk y k)
			if _tmp27 := v.args[1]; _tmp27.op == 7 {
				if y := v.args[2]; true {
					if k := v.args[3]; true {
						return /* clobber v */ p.setssa(v, 144, nil, y, k), true
					}
				}
			}
			// (blend.v _ _ y (init)) -> (make.vk y (init))
			if y := v.args[2]; true {
				if _tmp28 := v.args[3]; _tmp28.op == 1 {
					return /* clobber v */ p.setssa(v, 144, nil, y, p.values[0]), true
				}
			}
			// (blend.v x k _ (false)) -> (make.vk x k)
			if x := v.args[0]; true {
				if k := v.args[1]; true {
					if _tmp29 := v.args[3]; _tmp29.op == 7 {
						return /* clobber v */ p.setssa(v, 144, nil, x, k), true
					}
				}
			}
		}
	case 185: /* add.f */
		if len(v.args) == 3 {
			// (add.f _tmp1:(broadcast.f imm) f k) -> (add.imm.f f k imm)
			if _tmp1 := v.args[0]; _tmp1.op == 151 {
				if f := v.args[1]; true {
					if k := v.args[2]; true {
						if imm := tof64(_tmp1.imm); true {
							return /* clobber v */ p.setssa(v, 187, imm, f, k), true
						}
					}
				}
			}
			// (add.f f _tmp2:(broadcast.f imm) k) -> (add.imm.f f k imm)
			if f := v.args[0]; true {
				if _tmp2 := v.args[1]; _tmp2.op == 151 {
					if k := v.args[2]; true {
						if imm := tof64(_tmp2.imm); true {
							return /* clobber v */ p.setssa(v, 187, imm, f, k), true
						}
					}
				}
			}
		}
	case 187: /* add.imm.f */
		if len(v.args) == 2 {
			// (add.imm.f f _ 0) -> f
			if f := v.args[0]; true {
				if tof64(v.imm) == 0 {
					return f, true
				}
			}
		}
	case 188: /* add.imm.i */
		if len(v.args) == 2 {
			// (add.imm.i i _ 0) -> i
			if i := v.args[0]; true {
				if toi64(v.imm) == 0 {
					return i, true
				}
			}
		}
	case 189: /* sub.f */
		if len(v.args) == 3 {
			// (sub.f _tmp3:(broadcast.f imm) f k) -> (rsub.imm.f f k imm)
			if _tmp3 := v.args[0]; _tmp3.op == 151 {
				if f := v.args[1]; true {
					if k := v.args[2]; true {
						if imm := tof64(_tmp3.imm); true {
							return /* clobber v */ p.setssa(v, 195, imm, f, k), true
						}
					}
				}
			}
			// (sub.f f _tmp4:(broadcast.f imm) k) -> (sub.imm.f f k imm)
			if f := v.args[0]; true {
				if _tmp4 := v.args[1]; _tmp4.op == 151 {
					if k := v.args[2]; true {
						if imm := tof64(_tmp4.imm); true {
							return /* clobber v */ p.setssa(v, 191, imm, f, k), true
						}
					}
				}
			}
		}
	case 191: /* sub.imm.f */
		if len(v.args) == 2 {
			// (sub.imm.f f _ 0) -> f
			if f := v.args[0]; true {
				if tof64(v.imm) == 0 {
					return f, true
				}
			}
		}
	case 192: /* sub.imm.i */
		if len(v.args) == 2 {
			// (sub.imm.i i _ 0) -> i
			if i := v.args[0]; true {
				if toi64(v.imm) == 0 {
					return i, true
				}
			}
		}
	case 195: /* rsub.imm.f */
		if len(v.args) == 2 {
			// (rsub.imm.f f k 0) -> (neg.f f k)
			if f := v.args[0]; true {
				if k := v.args[1]; true {
					if tof64(v.imm) == 0 {
						return /* clobber v */ p.setssa(v, 155, nil, f, k), true
					}
				}
			}
		}
	case 196: /* rsub.imm.i */
		if len(v.args) == 2 {
			// (rsub.imm.i i k 0) -> (neg.i i k)
			if i := v.args[0]; true {
				if k := v.args[1]; true {
					if toi64(v.imm) == 0 {
						return /* clobber v */ p.setssa(v, 156, nil, i, k), true
					}
				}
			}
		}
	case 197: /* mul.f */
		if len(v.args) == 3 {
			// (mul.f _tmp5:(broadcast.f imm) f k) -> (mul.imm.f f k imm)
			if _tmp5 := v.args[0]; _tmp5.op == 151 {
				if f := v.args[1]; true {
					if k := v.args[2]; true {
						if imm := tof64(_tmp5.imm); true {
							return /* clobber v */ p.setssa(v, 199, imm, f, k), true
						}
					}
				}
			}
			// (mul.f f _tmp6:(broadcast.f imm) k) -> (mul.imm.f f k imm)
			if f := v.args[0]; true {
				if _tmp6 := v.args[1]; _tmp6.op == 151 {
					if k := v.args[2]; true {
						if imm := tof64(_tmp6.imm); true {
							return /* clobber v */ p.setssa(v, 199, imm, f, k), true
						}
					}
				}
			}
		}
	case 199: /* mul.imm.f */
		if len(v.args) == 2 {
			// (mul.imm.f f _ 1) -> f
			if f := v.args[0]; true {
				if tof64(v.imm) == 1 {
					return f, true
				}
			}
		}
	case 200: /* mul.imm.i */
		if len(v.args) == 2 {
			// (mul.imm.i i _ 1) -> i
			if i := v.args[0]; true {
				if toi64(v.imm) == 1 {
					return i, true
				}
			}
		}
	case 201: /* div.f */
		if len(v.args) == 3 {
			// (div.f f _tmp7:(broadcast.f imm) k) -> (div.imm.f f k imm)
			if f := v.args[0]; true {
				if _tmp7 := v.args[1]; _tmp7.op == 151 {
					if k := v.args[2]; true {
						if imm := tof64(_tmp7.imm); true {
							return /* clobber v */ p.setssa(v, 203, imm, f, k), true
						}
					}
				}
			}
			// (div.f _tmp8:(broadcast.f imm) f k) -> (rdiv.imm.f f k imm)
			if _tmp8 := v.args[0]; _tmp8.op == 151 {
				if f := v.args[1]; true {
					if k := v.args[2]; true {
						if imm := tof64(_tmp8.imm); true {
							return /* clobber v */ p.setssa(v, 205, imm, f, k), true
						}
					}
				}
			}
		}
	case 224: /* or.imm.i */
		if len(v.args) == 2 {
			// (or.imm.i i _ 0) -> i
			if i := v.args[0]; true {
				if toi64(v.imm) == 0 {
					return i, true
				}
			}
		}
	case 228: /* sll.imm.i */
		if len(v.args) == 2 {
			// (sll.imm.i i _ 0) -> i
			if i := v.args[0]; true {
				if toi64(v.imm) == 0 {
					return i, true
				}
			}
		}
	case 230: /* sra.imm.i */
		if len(v.args) == 2 {
			// (sra.imm.i i _ 0) -> i
			if i := v.args[0]; true {
				if toi64(v.imm) == 0 {
					return i, true
				}
			}
		}
	case 232: /* srl.imm.i */
		if len(v.args) == 2 {
			// (srl.imm.i i _ 0) -> i
			if i := v.args[0]; true {
				if toi64(v.imm) == 0 {
					return i, true
				}
			}
		}
	case 239: /* aggand.k */
		if len(v.args) == 3 {
			// (aggand.k mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp30 := v.args[2]; _tmp30.op == 7 {
					return mem, true
				}
			}
		}
	case 240: /* aggor.k */
		if len(v.args) == 3 {
			// (aggor.k mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp31 := v.args[2]; _tmp31.op == 7 {
					return mem, true
				}
			}
		}
	case 241: /* aggsum.f */
		if len(v.args) == 3 {
			// (aggsum.f mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp32 := v.args[2]; _tmp32.op == 7 {
					return mem, true
				}
			}
		}
	case 242: /* aggsum.i */
		if len(v.args) == 3 {
			// (aggsum.i mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp33 := v.args[2]; _tmp33.op == 7 {
					return mem, true
				}
			}
		}
	case 245: /* aggmin.f */
		if len(v.args) == 3 {
			// (aggmin.f mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp34 := v.args[2]; _tmp34.op == 7 {
					return mem, true
				}
			}
		}
	case 246: /* aggmin.i */
		if len(v.args) == 3 {
			// (aggmin.i mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp35 := v.args[2]; _tmp35.op == 7 {
					return mem, true
				}
			}
		}
	case 247: /* aggmax.f */
		if len(v.args) == 3 {
			// (aggmax.f mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp36 := v.args[2]; _tmp36.op == 7 {
					return mem, true
				}
			}
		}
	case 248: /* aggmax.i */
		if len(v.args) == 3 {
			// (aggmax.i mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp37 := v.args[2]; _tmp37.op == 7 {
					return mem, true
				}
			}
		}
	case 249: /* aggmin.ts */
		if len(v.args) == 3 {
			// (aggmin.ts mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp38 := v.args[2]; _tmp38.op == 7 {
					return mem, true
				}
			}
		}
	case 250: /* aggmax.ts */
		if len(v.args) == 3 {
			// (aggmax.ts mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp39 := v.args[2]; _tmp39.op == 7 {
					return mem, true
				}
			}
		}
	case 251: /* aggand.i */
		if len(v.args) == 3 {
			// (aggand.i mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp40 := v.args[2]; _tmp40.op == 7 {
					return mem, true
				}
			}
		}
	case 252: /* aggor.i */
		if len(v.args) == 3 {
			// (aggor.i mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp41 := v.args[2]; _tmp41.op == 7 {
					return mem, true
				}
			}
		}
	case 253: /* aggxor.i */
		if len(v.args) == 3 {
			// (aggxor.i mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp42 := v.args[2]; _tmp42.op == 7 {
					return mem, true
				}
			}
		}
	case 254: /* aggcount */
		if len(v.args) == 2 {
			// (aggcount mem (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp43 := v.args[1]; _tmp43.op == 7 {
					return mem, true
				}
			}
		}
	case 256: /* aggslotand.k */
		if len(v.args) == 4 {
			// (aggslotand.k mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp44 := v.args[3]; _tmp44.op == 7 {
					return mem, true
				}
			}
		}
	case 257: /* aggslotor.k */
		if len(v.args) == 4 {
			// (aggslotor.k mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp45 := v.args[3]; _tmp45.op == 7 {
					return mem, true
				}
			}
		}
	case 262: /* aggslotmin.f */
		if len(v.args) == 4 {
			// (aggslotmin.f mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp46 := v.args[3]; _tmp46.op == 7 {
					return mem, true
				}
			}
		}
	case 263: /* aggslotmin.i */
		if len(v.args) == 4 {
			// (aggslotmin.i mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp47 := v.args[3]; _tmp47.op == 7 {
					return mem, true
				}
			}
		}
	case 264: /* aggslotmax.f */
		if len(v.args) == 4 {
			// (aggslotmax.f mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp48 := v.args[3]; _tmp48.op == 7 {
					return mem, true
				}
			}
		}
	case 265: /* aggslotmax.i */
		if len(v.args) == 4 {
			// (aggslotmax.i mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp49 := v.args[3]; _tmp49.op == 7 {
					return mem, true
				}
			}
		}
	case 266: /* aggslotmin.ts */
		if len(v.args) == 4 {
			// (aggslotmin.ts mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp50 := v.args[3]; _tmp50.op == 7 {
					return mem, true
				}
			}
		}
	case 267: /* aggslotmax.ts */
		if len(v.args) == 4 {
			// (aggslotmax.ts mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp51 := v.args[3]; _tmp51.op == 7 {
					return mem, true
				}
			}
		}
	case 268: /* aggslotand.i */
		if len(v.args) == 4 {
			// (aggslotand.i mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp52 := v.args[3]; _tmp52.op == 7 {
					return mem, true
				}
			}
		}
	case 269: /* aggslotor.i */
		if len(v.args) == 4 {
			// (aggslotor.i mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp53 := v.args[3]; _tmp53.op == 7 {
					return mem, true
				}
			}
		}
	case 270: /* aggslotxor.i */
		if len(v.args) == 4 {
			// (aggslotxor.i mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp54 := v.args[3]; _tmp54.op == 7 {
					return mem, true
				}
			}
		}
	case 271: /* aggslotcount */
		if len(v.args) == 3 {
			// (aggslotcount mem _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp55 := v.args[2]; _tmp55.op == 7 {
					return mem, true
				}
			}
		}
	case 319: /* boxint */
		if len(v.args) == 2 {
			// (boxint _tmp9:(broadcast.i lit) _) -> (literal lit)
			if _tmp9 := v.args[0]; _tmp9.op == 152 {
				if lit := toi64(_tmp9.imm); true {
					return /* clobber v */ p.setssa(v, 130, lit), true
				}
			}
		}
	case 320: /* boxfloat */
		if len(v.args) == 2 {
			// (boxfloat _tmp10:(broadcast.f lit) _) -> (literal lit)
			if _tmp10 := v.args[0]; _tmp10.op == 151 {
				if lit := tof64(_tmp10.imm); true {
					return /* clobber v */ p.setssa(v, 130, lit), true
				}
			}
		}
	case 322: /* boxts */
		if len(v.args) == 2 {
			// (boxts _tmp11:(broadcast.ts lit) _), "ts := date.UnixMicro(int64(lit)); true" -> (literal ts)
			if _tmp11 := v.args[0]; _tmp11.op == 272 {
				if lit := toi64(_tmp11.imm); true {
					if ts := date.UnixMicro(int64(lit)); true {
						return /* clobber v */ p.setssa(v, 130, ts), true
					}
				}
			}
		}
	case 329: /* aggapproxcount */
		if len(v.args) == 2 {
			// (aggapproxcount mem (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp56 := v.args[1]; _tmp56.op == 7 {
					return mem, true
				}
			}
		}
	case 330: /* aggapproxcount.partial */
		if len(v.args) == 2 {
			// (aggapproxcount.partial mem (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp57 := v.args[1]; _tmp57.op == 7 {
					return mem, true
				}
			}
		}
	case 331: /* aggapproxcount.merge */
		if len(v.args) == 2 {
			// (aggapproxcount.merge mem (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp58 := v.args[1]; _tmp58.op == 7 {
					return mem, true
				}
			}
		}
	case 332: /* aggslotapproxcount */
		if len(v.args) == 4 {
			// (aggslotapproxcount mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp59 := v.args[3]; _tmp59.op == 7 {
					return mem, true
				}
			}
		}
	case 333: /* aggslotapproxcount.partial */
		if len(v.args) == 4 {
			// (aggslotapproxcount.partial mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp60 := v.args[3]; _tmp60.op == 7 {
					return mem, true
				}
			}
		}
	case 334: /* aggslotapproxcount.merge */
		if len(v.args) == 4 {
			// (aggslotapproxcount.merge mem _ _ (false) _) -> mem
			if mem := v.args[0]; true {
				if _tmp61 := v.args[3]; _tmp61.op == 7 {
					return mem, true
				}
			}
		}
	}
	return v, false
}
