nameOverride: ""
fullnameOverride: ""

snellerd:
  #name: snellerd
  #serviceAccountName: snellerd
  replicaCount: 3
  repository: snellerinc/snellerd
  tag: latest
  pullPolicy: IfNotPresent
  serviceType: ClusterIP
  ports:
    snellerd: 8000
    internode: 8001
  # Note that `maxCacheDirSize` only works when `SizeMemoryBackedVolumes`
  # feature gate is enabled (default from K8s v1.22+).
  maxCacheDirSize: 1Gi
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  serviceLabels: {}
  serviceAnnotations: {}
  headlessServiceLabels: {}
  headlessServiceAnnotations: {}

sdb:
  #name: sdb
  #serviceAccountName: sdb
  repository: snellerinc/sdb
  tag: latest
  pullPolicy: IfNotPresent
  cronJob: "* * * * *"
  database: default
  tablePattern: "*"
  batchSize: "1073741824"

ingress:
  enabled: false
  # ingressClassName: ""
  hosts: []
  tls: []
  #  - secretName: sneller-tls
  #    hosts:
  #      - sneller-example.local
  annotations: {}

secrets:
  s3:
    useExistingSecret: false
    #secretName: sneller-aws
    values:
      awsRegion: us-east-1
      awsAccessKeyId: ""
      awsSecretAccessKey: ""
  token:
    useExistingSecret: false
    #secretName: sneller-token
    values:
      snellerToken:        # When it's empty, then a random Sneller token will be created
  index:
    useExistingSecret: false
    #secretName: sneller-index
    values:
      snellerIndexKey: ""

configuration:
  #name:
  values:
    s3EndPoint: ""
    s3Bucket: ""
