// Code generated by goyacc partiql.y. DO NOT EDIT.

//line partiql.y:15
// Copyright (C) 2022 Sneller, Inc.
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package partiql

import (
	__yyfmt__ "fmt"

	"github.com/SnellerInc/sneller/expr"
) //line partiql.y:29

//line partiql.y:36
type yySymType struct {
	yys      int
	bytes    []byte
	str      string
	yesno    bool
	integer  int
	exprint  *expr.Integer
	expr     expr.Node
	pc       expr.PathComponent
	order    expr.Order
	sel      *expr.Select
	bind     expr.Binding
	jk       expr.JoinKind
	from     expr.From
	with     []expr.CTE
	bindings []expr.Binding
	limbs    []expr.CaseLimb
	values   []expr.Node
	orders   []expr.Order
}

const ERROR = 57346
const EOF = 57347
const UNION = 57348
const SELECT = 57349
const FROM = 57350
const WHERE = 57351
const GROUP = 57352
const ORDER = 57353
const BY = 57354
const HAVING = 57355
const LIMIT = 57356
const OFFSET = 57357
const WITH = 57358
const INTO = 57359
const DISTINCT = 57360
const ALL = 57361
const AS = 57362
const EXISTS = 57363
const NULLS = 57364
const FIRST = 57365
const LAST = 57366
const ASC = 57367
const DESC = 57368
const VALUE = 57369
const COUNT = 57370
const MIN = 57371
const MAX = 57372
const SUM = 57373
const AVG = 57374
const BIT_AND = 57375
const BIT_OR = 57376
const BIT_XOR = 57377
const BOOL_AND = 57378
const BOOL_OR = 57379
const COALESCE = 57380
const NULLIF = 57381
const EXTRACT = 57382
const DATE_TRUNC = 57383
const CAST = 57384
const UTCNOW = 57385
const DATE_ADD = 57386
const DATE_DIFF = 57387
const EARLIEST = 57388
const LATEST = 57389
const JOIN = 57390
const LEFT = 57391
const RIGHT = 57392
const CROSS = 57393
const INNER = 57394
const OUTER = 57395
const FULL = 57396
const ON = 57397
const ID = 57398
const NULL = 57399
const TRUE = 57400
const FALSE = 57401
const MISSING = 57402
const OR = 57403
const AND = 57404
const NOT = 57405
const BETWEEN = 57406
const CASE = 57407
const WHEN = 57408
const THEN = 57409
const ELSE = 57410
const END = 57411
const EQ = 57412
const NE = 57413
const LT = 57414
const LE = 57415
const GT = 57416
const GE = 57417
const ILIKE = 57418
const LIKE = 57419
const IN = 57420
const IS = 57421
const SHIFT_LEFT_LOGICAL = 57422
const SHIFT_RIGHT_ARITHMETIC = 57423
const SHIFT_RIGHT_LOGICAL = 57424
const CONCAT = 57425
const APPEND = 57426
const NEGATION_PRECEDENCE = 57427
const NUMBER = 57428
const ION = 57429
const STRING = 57430

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ERROR",
	"EOF",
	"UNION",
	"SELECT",
	"FROM",
	"WHERE",
	"GROUP",
	"ORDER",
	"BY",
	"HAVING",
	"LIMIT",
	"OFFSET",
	"WITH",
	"INTO",
	"DISTINCT",
	"ALL",
	"AS",
	"EXISTS",
	"NULLS",
	"FIRST",
	"LAST",
	"ASC",
	"DESC",
	"VALUE",
	"COUNT",
	"MIN",
	"MAX",
	"SUM",
	"AVG",
	"BIT_AND",
	"BIT_OR",
	"BIT_XOR",
	"BOOL_AND",
	"BOOL_OR",
	"COALESCE",
	"NULLIF",
	"EXTRACT",
	"DATE_TRUNC",
	"CAST",
	"UTCNOW",
	"DATE_ADD",
	"DATE_DIFF",
	"EARLIEST",
	"LATEST",
	"JOIN",
	"LEFT",
	"RIGHT",
	"CROSS",
	"INNER",
	"OUTER",
	"FULL",
	"ON",
	"ID",
	"'('",
	"','",
	"')'",
	"'['",
	"']'",
	"'{'",
	"'}'",
	"NULL",
	"TRUE",
	"FALSE",
	"MISSING",
	"OR",
	"AND",
	"'!'",
	"'~'",
	"NOT",
	"BETWEEN",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"EQ",
	"NE",
	"LT",
	"LE",
	"GT",
	"GE",
	"ILIKE",
	"LIKE",
	"IN",
	"IS",
	"'|'",
	"'^'",
	"'&'",
	"SHIFT_LEFT_LOGICAL",
	"SHIFT_RIGHT_ARITHMETIC",
	"SHIFT_RIGHT_LOGICAL",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"CONCAT",
	"APPEND",
	"NEGATION_PRECEDENCE",
	"'.'",
	"NUMBER",
	"ION",
	"STRING",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 317,
	68, 73,
	69, 73,
	72, 73,
	73, 73,
	79, 73,
	80, 73,
	81, 73,
	82, 73,
	83, 73,
	84, 73,
	-2, 111,
}

const yyPrivate = 57344

const yyLast = 2017

var yyAct = [...]int16{
	15, 311, 315, 304, 193, 296, 254, 282, 201, 13,
	124, 110, 9, 180, 216, 146, 145, 39, 195, 113,
	73, 74, 7, 154, 11, 235, 14, 17, 177, 119,
	178, 101, 215, 60, 68, 69, 70, 71, 72, 73,
	74, 250, 115, 116, 117, 249, 120, 63, 64, 65,
	67, 66, 68, 69, 70, 71, 72, 73, 74, 290,
	194, 266, 112, 132, 133, 134, 135, 136, 137, 138,
	139, 140, 141, 142, 143, 144, 129, 130, 147, 148,
	149, 150, 151, 152, 127, 123, 155, 156, 253, 164,
	165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
	175, 129, 179, 181, 183, 184, 8, 45, 195, 240,
	267, 153, 181, 126, 49, 47, 48, 50, 70, 71,
	72, 73, 74, 111, 251, 191, 113, 240, 247, 221,
	192, 200, 181, 197, 198, 157, 160, 161, 159, 217,
	219, 220, 218, 158, 196, 214, 240, 239, 189, 320,
	57, 245, 199, 212, 46, 52, 51, 53, 244, 243,
	121, 213, 6, 57, 222, 58, 131, 122, 114, 112,
	109, 108, 107, 106, 40, 105, 104, 103, 236, 237,
	102, 18, 20, 21, 19, 22, 23, 24, 25, 26,
	27, 31, 32, 37, 36, 33, 38, 34, 35, 28,
	29, 99, 98, 256, 248, 274, 57, 97, 252, 8,
	45, 96, 95, 94, 93, 92, 128, 49, 47, 48,
	50, 91, 90, 89, 43, 42, 88, 30, 55, 8,
	257, 258, 188, 129, 187, 186, 185, 285, 287, 271,
	286, 272, 273, 268, 275, 276, 277, 278, 263, 41,
	182, 261, 265, 264, 260, 259, 262, 46, 52, 51,
	327, 279, 280, 281, 329, 330, 54, 10, 12, 4,
	312, 288, 64, 65, 67, 66, 68, 69, 70, 71,
	72, 73, 74, 305, 298, 283, 300, 306, 284, 297,
	295, 255, 301, 302, 299, 207, 209, 210, 206, 208,
	202, 211, 303, 246, 126, 205, 203, 316, 317, 121,
	313, 310, 5, 100, 204, 314, 318, 319, 125, 326,
	40, 316, 324, 325, 321, 3, 328, 18, 20, 21,
	19, 22, 23, 24, 25, 26, 27, 31, 32, 37,
	36, 33, 38, 34, 35, 28, 29, 2, 118, 176,
	56, 44, 1, 0, 0, 8, 45, 0, 190, 0,
	0, 0, 0, 49, 47, 48, 50, 0, 0, 0,
	43, 42, 0, 30, 75, 76, 61, 87, 62, 63,
	64, 65, 67, 66, 68, 69, 70, 71, 72, 73,
	74, 0, 0, 0, 0, 41, 182, 163, 0, 0,
	40, 0, 0, 46, 52, 51, 0, 18, 20, 21,
	19, 22, 23, 24, 25, 26, 27, 31, 32, 37,
	36, 33, 38, 34, 35, 28, 29, 0, 0, 0,
	0, 0, 0, 0, 0, 8, 45, 0, 0, 0,
	0, 0, 0, 49, 47, 48, 50, 0, 0, 0,
	43, 42, 0, 30, 65, 67, 66, 68, 69, 70,
	71, 72, 73, 74, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 41, 162, 0, 0, 40,
	0, 0, 0, 46, 52, 51, 18, 20, 21, 19,
	22, 23, 24, 25, 26, 27, 31, 32, 37, 36,
	33, 38, 34, 35, 28, 29, 0, 0, 0, 0,
	0, 0, 0, 0, 8, 45, 0, 0, 0, 0,
	0, 0, 49, 47, 48, 50, 0, 0, 0, 43,
	42, 0, 30, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 41, 16, 0, 0, 40, 0,
	0, 0, 46, 52, 51, 18, 20, 21, 19, 22,
	23, 24, 25, 26, 27, 31, 32, 37, 36, 33,
	38, 34, 35, 28, 29, 0, 0, 0, 0, 0,
	0, 0, 0, 8, 45, 0, 0, 0, 0, 0,
	0, 49, 47, 48, 50, 0, 0, 0, 43, 42,
	0, 30, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 121, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 41, 182, 0, 0, 40, 0, 0,
	0, 46, 52, 51, 18, 20, 21, 19, 22, 23,
	24, 25, 26, 27, 31, 32, 37, 36, 33, 38,
	34, 35, 28, 29, 0, 0, 0, 0, 0, 0,
	0, 0, 8, 45, 0, 0, 0, 0, 0, 0,
	49, 47, 48, 50, 0, 0, 0, 43, 42, 0,
	30, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 41, 0, 0, 0, 40, 0, 0, 0,
	46, 52, 51, 18, 20, 21, 19, 22, 23, 24,
	25, 26, 27, 31, 32, 37, 36, 33, 38, 34,
	35, 28, 29, 0, 0, 0, 0, 0, 0, 322,
	323, 8, 45, 0, 0, 0, 0, 0, 0, 49,
	47, 48, 50, 0, 0, 0, 43, 42, 0, 30,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	59, 41, 86, 85, 0, 0, 84, 83, 0, 46,
	52, 51, 0, 77, 78, 79, 80, 81, 82, 75,
	76, 61, 87, 62, 63, 64, 65, 67, 66, 68,
	69, 70, 71, 72, 73, 74, 8, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 86, 85,
	0, 0, 84, 83, 0, 0, 0, 0, 0, 77,
	78, 79, 80, 81, 82, 75, 76, 61, 87, 62,
	63, 64, 65, 67, 66, 68, 69, 70, 71, 72,
	73, 74, 309, 0, 0, 0, 0, 0, 0, 0,
	0, 86, 85, 0, 0, 84, 83, 0, 0, 0,
	0, 0, 77, 78, 79, 80, 81, 82, 75, 76,
	61, 87, 62, 63, 64, 65, 67, 66, 68, 69,
	70, 71, 72, 73, 74, 308, 0, 0, 0, 0,
	0, 0, 0, 0, 86, 85, 0, 0, 84, 83,
	0, 0, 0, 0, 0, 77, 78, 79, 80, 81,
	82, 75, 76, 61, 87, 62, 63, 64, 65, 67,
	66, 68, 69, 70, 71, 72, 73, 74, 294, 0,
	0, 0, 0, 0, 0, 0, 0, 86, 85, 0,
	0, 84, 83, 0, 0, 0, 0, 0, 77, 78,
	79, 80, 81, 82, 75, 76, 61, 87, 62, 63,
	64, 65, 67, 66, 68, 69, 70, 71, 72, 73,
	74, 293, 0, 0, 0, 0, 0, 0, 0, 0,
	86, 85, 0, 0, 84, 83, 0, 0, 0, 0,
	0, 77, 78, 79, 80, 81, 82, 75, 76, 61,
	87, 62, 63, 64, 65, 67, 66, 68, 69, 70,
	71, 72, 73, 74, 292, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 86, 85, 0, 0, 84, 83,
	0, 0, 0, 0, 0, 77, 78, 79, 80, 81,
	82, 75, 76, 61, 87, 62, 63, 64, 65, 67,
	66, 68, 69, 70, 71, 72, 73, 74, 291, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 86, 85,
	0, 0, 84, 83, 0, 0, 0, 0, 0, 77,
	78, 79, 80, 81, 82, 75, 76, 61, 87, 62,
	63, 64, 65, 67, 66, 68, 69, 70, 71, 72,
	73, 74, 289, 0, 0, 0, 0, 0, 0, 0,
	0, 86, 85, 0, 0, 84, 83, 0, 0, 0,
	0, 0, 77, 78, 79, 80, 81, 82, 75, 76,
	61, 87, 62, 63, 64, 65, 67, 66, 68, 69,
	70, 71, 72, 73, 74, 86, 85, 0, 0, 84,
	83, 0, 0, 270, 0, 0, 77, 78, 79, 80,
	81, 82, 75, 76, 61, 87, 62, 63, 64, 65,
	67, 66, 68, 69, 70, 71, 72, 73, 74, 269,
	242, 0, 0, 0, 0, 0, 0, 0, 86, 85,
	0, 0, 84, 83, 0, 0, 0, 0, 0, 77,
	78, 79, 80, 81, 82, 75, 76, 61, 87, 62,
	63, 64, 65, 67, 66, 68, 69, 70, 71, 72,
	73, 74, 0, 0, 0, 0, 0, 0, 86, 85,
	0, 0, 84, 83, 0, 0, 0, 0, 0, 77,
	78, 79, 80, 81, 82, 75, 76, 61, 87, 62,
	63, 64, 65, 67, 66, 68, 69, 70, 71, 72,
	73, 74, 241, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 86, 85, 0, 0, 84, 83, 0, 0,
	0, 0, 0, 77, 78, 79, 80, 81, 82, 75,
	76, 61, 87, 62, 63, 64, 65, 67, 66, 68,
	69, 70, 71, 72, 73, 74, 86, 85, 0, 0,
	84, 83, 0, 0, 238, 0, 0, 77, 78, 79,
	80, 81, 82, 75, 76, 61, 87, 62, 63, 64,
	65, 67, 66, 68, 69, 70, 71, 72, 73, 74,
	234, 0, 0, 0, 0, 0, 0, 0, 0, 86,
	85, 0, 0, 84, 83, 0, 0, 0, 0, 0,
	77, 78, 79, 80, 81, 82, 75, 76, 61, 87,
	62, 63, 64, 65, 67, 66, 68, 69, 70, 71,
	72, 73, 74, 233, 0, 0, 0, 0, 0, 0,
	0, 0, 86, 85, 0, 0, 84, 83, 0, 0,
	0, 0, 0, 77, 78, 79, 80, 81, 82, 75,
	76, 61, 87, 62, 63, 64, 65, 67, 66, 68,
	69, 70, 71, 72, 73, 74, 232, 0, 0, 0,
	0, 0, 0, 0, 0, 86, 85, 0, 0, 84,
	83, 0, 0, 0, 0, 0, 77, 78, 79, 80,
	81, 82, 75, 76, 61, 87, 62, 63, 64, 65,
	67, 66, 68, 69, 70, 71, 72, 73, 74, 231,
	0, 0, 0, 0, 0, 0, 0, 0, 86, 85,
	0, 0, 84, 83, 0, 0, 0, 0, 0, 77,
	78, 79, 80, 81, 82, 75, 76, 61, 87, 62,
	63, 64, 65, 67, 66, 68, 69, 70, 71, 72,
	73, 74, 230, 0, 0, 0, 0, 0, 0, 0,
	0, 86, 85, 0, 0, 84, 83, 0, 0, 0,
	0, 0, 77, 78, 79, 80, 81, 82, 75, 76,
	61, 87, 62, 63, 64, 65, 67, 66, 68, 69,
	70, 71, 72, 73, 74, 229, 0, 0, 0, 0,
	0, 0, 0, 0, 86, 85, 0, 0, 84, 83,
	0, 0, 0, 0, 0, 77, 78, 79, 80, 81,
	82, 75, 76, 61, 87, 62, 63, 64, 65, 67,
	66, 68, 69, 70, 71, 72, 73, 74, 228, 0,
	0, 0, 0, 0, 0, 0, 0, 86, 85, 0,
	0, 84, 83, 0, 0, 0, 0, 0, 77, 78,
	79, 80, 81, 82, 75, 76, 61, 87, 62, 63,
	64, 65, 67, 66, 68, 69, 70, 71, 72, 73,
	74, 227, 0, 0, 0, 0, 0, 0, 0, 0,
	86, 85, 0, 0, 84, 83, 0, 0, 0, 0,
	0, 77, 78, 79, 80, 81, 82, 75, 76, 61,
	87, 62, 63, 64, 65, 67, 66, 68, 69, 70,
	71, 72, 73, 74, 226, 0, 0, 0, 0, 0,
	0, 0, 0, 86, 85, 0, 0, 84, 83, 0,
	0, 0, 0, 0, 77, 78, 79, 80, 81, 82,
	75, 76, 61, 87, 62, 63, 64, 65, 67, 66,
	68, 69, 70, 71, 72, 73, 74, 225, 0, 0,
	0, 0, 0, 0, 0, 0, 86, 85, 0, 0,
	84, 83, 0, 0, 0, 0, 0, 77, 78, 79,
	80, 81, 82, 75, 76, 61, 87, 62, 63, 64,
	65, 67, 66, 68, 69, 70, 71, 72, 73, 74,
	224, 0, 0, 0, 0, 0, 0, 0, 0, 86,
	85, 0, 0, 84, 83, 0, 0, 0, 0, 0,
	77, 78, 79, 80, 81, 82, 75, 76, 61, 87,
	62, 63, 64, 65, 67, 66, 68, 69, 70, 71,
	72, 73, 74, 223, 0, 0, 0, 0, 0, 0,
	0, 0, 86, 85, 0, 0, 84, 83, 0, 0,
	0, 0, 0, 77, 78, 79, 80, 81, 82, 75,
	76, 61, 87, 62, 63, 64, 65, 67, 66, 68,
	69, 70, 71, 72, 73, 74, 86, 85, 0, 0,
	84, 83, 0, 0, 0, 0, 0, 307, 78, 79,
	80, 81, 82, 75, 76, 61, 87, 62, 63, 64,
	65, 67, 66, 68, 69, 70, 71, 72, 73, 74,
	86, 85, 0, 0, 84, 83, 0, 0, 0, 0,
	0, 77, 78, 79, 80, 81, 82, 75, 76, 61,
	87, 62, 63, 64, 65, 67, 66, 68, 69, 70,
	71, 72, 73, 74, 85, 0, 0, 84, 83, 0,
	0, 0, 0, 0, 77, 78, 79, 80, 81, 82,
	75, 76, 61, 87, 62, 63, 64, 65, 67, 66,
	68, 69, 70, 71, 72, 73, 74, 84, 83, 0,
	0, 0, 0, 0, 77, 78, 79, 80, 81, 82,
	75, 76, 61, 87, 62, 63, 64, 65, 67, 66,
	68, 69, 70, 71, 72, 73, 74,
}

var yyPact = [...]int16{
	253, -1000, 305, 104, 173, 249, 173, 248, -1000, 458,
	-1000, 246, 171, 148, -1000, 770, -1000, -1000, 169, 166,
	165, 164, 158, 157, 156, 155, 154, 150, 145, 144,
	-44, 123, 120, 119, 118, 116, 115, 114, 113, 66,
	111, 695, 695, 695, -1000, 616, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 110, 302, 296, 458, 173, 173,
	-1000, 109, 695, 695, 695, 695, 695, 695, 695, 695,
	695, 695, 695, 695, 695, -90, -91, 695, 695, 695,
	695, 695, 695, 50, -63, 695, 695, 71, 379, 695,
	695, 695, 695, 695, 695, 695, 695, 695, 695, 695,
	-47, 695, 537, 695, 695, 180, 179, 178, 176, 89,
	-1000, 299, 173, 4, 302, -1000, 1915, 1915, 74, -1000,
	1852, 249, 302, 72, 291, 247, 458, -1000, -1000, -41,
	-1000, 153, -43, 181, 362, -61, -61, -61, 21, 21,
	-80, -80, -80, -1000, -1000, -1000, -1000, 289, 289, 289,
	289, 289, 289, -37, -92, 1915, 1885, -1000, 75, -1000,
	-1000, -1000, 70, 695, 1784, 1741, 1698, 1655, 1612, 1569,
	1526, 1483, 1440, 1397, 1354, 1311, -53, 695, 695, 1268,
	88, 1852, -1000, 1234, 1190, 101, 100, 93, 295, -1000,
	-1000, 69, -41, -16, -20, -1000, 65, -1000, 458, 29,
	-1000, 281, 695, 458, 458, -1000, 207, -1000, 206, 203,
	200, 204, -1000, 2, 51, 50, -1000, -1000, -1000, -1000,
	-1000, -1000, 1150, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 1107, 1852, 695, -1000,
	695, 695, 149, 695, 695, 695, 695, -1000, -1000, -41,
	-41, -1000, 105, -1000, 272, 276, 1852, -1000, 182, -1000,
	-1000, -1000, 192, -1000, 190, -1000, -1000, -1000, -1000, -1000,
	695, 1852, 1852, 1073, 0, 1030, 986, 942, 899, -1000,
	-1000, 291, 278, 695, 458, 695, -1000, -1000, 1852, -1000,
	-1000, 695, 695, -1000, -1000, 281, 269, 275, 1852, 92,
	1818, 856, 813, 272, 255, -86, 695, 695, -1000, -1000,
	278, -1000, -86, -1000, 91, -1000, 724, 289, 269, -1000,
	695, 238, -1000, -1000, 255, -1000, -1000, 241, -1000, -1000,
	-1000,
}

var yyPgo = [...]int16{
	0, 352, 0, 351, 27, 157, 350, 8, 7, 349,
	348, 347, 325, 11, 324, 319, 12, 17, 4, 29,
	6, 9, 26, 10, 318, 13, 2, 5, 315, 314,
	3, 1, 313, 306,
}

var yyR1 = [...]int8{
	0, 1, 19, 6, 6, 11, 11, 12, 12, 22,
	22, 22, 22, 5, 3, 3, 3, 3, 3, 3,
	3, 3, 4, 4, 10, 10, 16, 16, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 21, 21, 25, 25, 25, 29, 29,
	29, 29, 29, 29, 29, 33, 33, 23, 23, 24,
	24, 24, 18, 13, 13, 13, 13, 17, 9, 9,
	32, 32, 7, 7, 8, 8, 20, 20, 15, 15,
	15, 14, 14, 14, 26, 28, 28, 27, 27, 30,
	30, 31, 31,
}

var yyR2 = [...]int8{
	0, 12, 10, 2, 0, 1, 0, 6, 7, 3,
	2, 1, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 1, 1, 1, 0, 1, 4,
	5, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 6, 6, 8, 8, 6,
	6, 3, 3, 4, 5, 5, 4, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	2, 3, 3, 3, 3, 3, 3, 3, 3, 5,
	4, 2, 2, 3, 3, 3, 4, 3, 4, 3,
	4, 3, 4, 1, 3, 1, 1, 3, 1, 2,
	2, 3, 2, 3, 2, 1, 2, 1, 0, 2,
	3, 7, 1, 0, 3, 4, 4, 1, 0, 2,
	4, 5, 0, 2, 0, 2, 0, 3, 0, 2,
	2, 0, 1, 1, 3, 3, 1, 0, 3, 0,
	2, 0, 2,
}

var yyChk = [...]int16{
	-1000, -1, -11, -12, 16, 7, 58, -17, 56, -16,
	18, -17, 20, -21, -22, -2, 97, -4, 28, 31,
	29, 30, 32, 33, 34, 35, 36, 37, 46, 47,
	74, 38, 39, 42, 44, 45, 41, 40, 43, -17,
	21, 96, 72, 71, -3, 57, 104, 65, 66, 64,
	67, 106, 105, -5, 20, 57, -6, 58, 17, 20,
	-17, 87, 89, 90, 91, 92, 94, 93, 95, 96,
	97, 98, 99, 100, 101, 85, 86, 79, 80, 81,
	82, 83, 84, 73, 72, 69, 68, 88, 57, 57,
	57, 57, 57, 57, 57, 57, 57, 57, 57, 57,
	-32, 75, 57, 57, 57, 57, 57, 57, 57, 57,
	-13, 57, 103, 60, 57, -2, -2, -2, -10, -19,
	-2, 7, 57, -19, -23, -24, 8, -22, -5, -17,
	-17, 57, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, 106, 106, -2, -2, -2,
	-2, -2, -2, -4, 86, -2, -2, 64, 72, 67,
	65, 66, 97, 18, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -9, 75, 77, -2,
	-25, -2, 97, -2, -2, 56, 56, 56, 56, 59,
	59, -25, -17, -18, 56, 104, -19, 59, -16, -19,
	59, -7, 9, -33, -29, 58, 51, 48, 52, 49,
	50, 54, -22, -19, -25, 69, 106, 64, 67, 65,
	66, 59, -2, 59, 59, 59, 59, 59, 59, 59,
	59, 59, 59, 59, 59, 78, -2, -2, 76, 59,
	58, 58, 20, 58, 58, 58, 8, 59, -13, 61,
	61, 59, -21, 59, -20, 10, -2, -22, -22, 48,
	48, 48, 53, 48, 53, 48, 59, 59, -4, 59,
	76, -2, -2, -2, 56, -2, -2, -2, -2, -13,
	-13, -23, -8, 13, 12, 55, 48, 48, -2, 59,
	59, 58, 58, 59, 59, -7, -27, 11, -2, -21,
	-2, -2, -2, -20, -30, 14, 12, 79, 59, 59,
	-8, -31, 15, -18, -28, -26, -2, -2, -27, -18,
	58, -14, 25, 26, -30, -26, -15, 22, -31, 23,
	24,
}

var yyDef = [...]int16{
	6, -2, 0, 5, 0, 27, 0, 0, 117, 0,
	26, 0, 0, 4, 93, 11, 12, 28, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 113,
	0, 0, 0, 0, 22, 0, 14, 15, 16, 17,
	18, 19, 20, 21, 0, 0, 108, 0, 0, 0,
	10, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	118, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	13, 0, 0, 0, 0, 70, 81, 82, 0, 24,
	25, 27, 0, 0, 122, 107, 0, 94, 3, 113,
	9, 0, 57, 58, 59, 60, 61, 62, 63, 64,
	65, 66, 67, 68, 69, 71, 72, 73, 74, 75,
	76, 77, 78, 0, 0, 83, 84, 85, 0, 87,
	89, 91, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 95, 96, 0, 0, 0, 0, 0, 0, 51,
	52, 0, 113, 0, 0, 112, 0, 23, 0, 0,
	7, 126, 0, 0, 0, 105, 0, 98, 0, 0,
	0, 0, 109, 0, 0, 0, 80, 86, 88, 90,
	92, 29, 0, 31, 32, 33, 34, 35, 36, 37,
	38, 39, 40, 41, 42, 43, 0, 119, 0, 44,
	0, 0, 0, 0, 0, 0, 0, 53, 114, 113,
	113, 56, 108, 8, 124, 0, 123, 110, 0, 106,
	99, 100, 0, 102, 0, 104, 54, 55, 79, 30,
	0, 120, 97, 0, 0, 0, 0, 0, 0, 115,
	116, 122, 137, 0, 0, 0, 101, 103, 121, 45,
	46, 0, 0, 49, 50, 126, 139, 0, 125, 127,
	0, 0, 0, 124, 141, 0, 0, 0, 47, 48,
	137, 1, 0, 140, 138, 136, 131, -2, 139, 142,
	0, 128, 132, 133, 141, 135, 134, 0, 2, 129,
	130,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 70, 3, 3, 3, 99, 91, 3,
	57, 59, 97, 95, 58, 96, 103, 98, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 60, 3, 61, 90, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 62, 89, 63, 71,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 64, 65, 66, 67, 68,
	69, 72, 73, 74, 75, 76, 77, 78, 79, 80,
	81, 82, 83, 84, 85, 86, 87, 88, 92, 93,
	94, 100, 101, 102, 104, 105, 106,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-12 : yypt+1]
//line partiql.y:114
		{
			yylex.(*scanner).with = yyDollar[1].with
			yylex.(*scanner).into = yyDollar[5].expr
			yylex.(*scanner).result = &expr.Select{Distinct: yyDollar[3].yesno, Columns: yyDollar[4].bindings, From: yyDollar[6].from, Where: yyDollar[7].expr, GroupBy: yyDollar[8].bindings, Having: yyDollar[9].expr, OrderBy: yyDollar[10].orders, Limit: yyDollar[11].exprint, Offset: yyDollar[12].exprint}
		}
	case 2:
		yyDollar = yyS[yypt-10 : yypt+1]
//line partiql.y:122
		{
			yyVAL.sel = &expr.Select{Distinct: yyDollar[2].yesno, Columns: yyDollar[3].bindings, From: yyDollar[4].from, Where: yyDollar[5].expr, GroupBy: yyDollar[6].bindings, Having: yyDollar[7].expr, OrderBy: yyDollar[8].orders, Limit: yyDollar[9].exprint, Offset: yyDollar[10].exprint}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:127
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:127
		{
			yyVAL.expr = nil
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:130
		{
			yyVAL.with = yyDollar[1].with
		}
	case 6:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:130
		{
			yyVAL.with = nil
		}
	case 7:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:133
		{
			yyVAL.with = []expr.CTE{{yyDollar[2].str, yyDollar[5].sel}}
		}
	case 8:
		yyDollar = yyS[yypt-7 : yypt+1]
//line partiql.y:134
		{
			yyVAL.with = append(yyDollar[1].with, expr.CTE{yyDollar[3].str, yyDollar[6].sel})
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:140
		{
			yyVAL.bind = expr.Bind(yyDollar[1].expr, yyDollar[3].str)
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:141
		{
			yyVAL.bind = expr.Bind(yyDollar[1].expr, yyDollar[2].str)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:142
		{
			yyVAL.bind = expr.Bind(yyDollar[1].expr, "")
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:143
		{
			yyVAL.bind = expr.Bind(expr.Star{}, "")
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:146
		{
			yyVAL.expr = &expr.Path{First: yyDollar[1].str, Rest: yyDollar[2].pc}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:150
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:151
		{
			yyVAL.expr = expr.Bool(true)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:152
		{
			yyVAL.expr = expr.Bool(false)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:153
		{
			yyVAL.expr = expr.Null{}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:154
		{
			yyVAL.expr = expr.Missing{}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:155
		{
			yyVAL.expr = expr.String(yyDollar[1].str)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:156
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:157
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:169
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:170
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:173
		{
			yyVAL.expr = yyDollar[1].sel
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:174
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:177
		{
			yyVAL.yesno = true
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:177
		{
			yyVAL.yesno = false
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:182
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:186
		{
			yyVAL.expr = expr.Count(expr.Star{})
		}
	case 30:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:190
		{
			yyVAL.expr = expr.CountDistinct(yyDollar[4].expr)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:194
		{
			yyVAL.expr = expr.Count(yyDollar[3].expr)
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:198
		{
			yyVAL.expr = expr.Sum(yyDollar[3].expr)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:202
		{
			yyVAL.expr = expr.Min(yyDollar[3].expr)
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:206
		{
			yyVAL.expr = expr.Max(yyDollar[3].expr)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:210
		{
			yyVAL.expr = expr.Avg(yyDollar[3].expr)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:214
		{
			yyVAL.expr = expr.AggregateAnd(yyDollar[3].expr)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:218
		{
			yyVAL.expr = expr.AggregateOr(yyDollar[3].expr)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:222
		{
			yyVAL.expr = expr.AggregateXor(yyDollar[3].expr)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:226
		{
			yyVAL.expr = expr.AggregateBoolAnd(yyDollar[3].expr)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:230
		{
			yyVAL.expr = expr.AggregateBoolOr(yyDollar[3].expr)
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:234
		{
			yyVAL.expr = expr.Earliest(yyDollar[3].expr)
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:238
		{
			yyVAL.expr = expr.Latest(yyDollar[3].expr)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:242
		{
			yyVAL.expr = &expr.Case{Limbs: yyDollar[2].limbs, Else: yyDollar[3].expr}
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:246
		{
			yyVAL.expr = expr.Coalesce(yyDollar[3].values)
		}
	case 45:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:250
		{
			yyVAL.expr = expr.NullIf(yyDollar[3].expr, yyDollar[5].expr)
		}
	case 46:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:254
		{
			nod, ok := buildCast(yyDollar[3].expr, yyDollar[5].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad CAST type %q", yyDollar[5].str))
				return 1
			}
			yyVAL.expr = nod
		}
	case 47:
		yyDollar = yyS[yypt-8 : yypt+1]
//line partiql.y:263
		{
			part, ok := timePart(yyDollar[3].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad DATE_ADD part %q", yyDollar[3].str))
			}
			yyVAL.expr = expr.DateAdd(part, yyDollar[5].expr, yyDollar[7].expr)
		}
	case 48:
		yyDollar = yyS[yypt-8 : yypt+1]
//line partiql.y:271
		{
			part, ok := timePart(yyDollar[3].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad DATE_DIFF part %q", yyDollar[3].str))
			}
			yyVAL.expr = expr.DateDiff(part, yyDollar[5].expr, yyDollar[7].expr)
		}
	case 49:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:279
		{
			part, ok := timePart(yyDollar[3].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad DATE_TRUNC part %q", yyDollar[3].str))
			}
			yyVAL.expr = expr.DateTrunc(part, yyDollar[5].expr)
		}
	case 50:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:287
		{
			part, ok := timePart(yyDollar[3].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad EXTRACT part %q", yyDollar[3].str))
			}
			yyVAL.expr = expr.DateExtract(part, yyDollar[5].expr)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:295
		{
			yyVAL.expr = yylex.(*scanner).utcnow()
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:299
		{
			op := expr.Call(yyDollar[1].str)
			if op.Private() {
				yylex.Error(__yyfmt__.Sprintf("cannot use reserved builtin %q", yyDollar[1].str))
			}
			yyVAL.expr = op
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:307
		{
			op := expr.Call(yyDollar[1].str, yyDollar[3].values...)
			if op.Private() {
				yylex.Error(__yyfmt__.Sprintf("cannot use reserved builtin %q", yyDollar[1].str))
			}
			yyVAL.expr = op
		}
	case 54:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:315
		{
			yyVAL.expr = expr.CallOp(expr.InSubquery, yyDollar[1].expr, yyDollar[4].sel)
		}
	case 55:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:319
		{
			yyVAL.expr = expr.In(yyDollar[1].expr, yyDollar[4].values...)
		}
	case 56:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:323
		{
			yyVAL.expr = exists(yyDollar[3].sel)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:327
		{
			yyVAL.expr = expr.BitOr(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:331
		{
			yyVAL.expr = expr.BitXor(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:335
		{
			yyVAL.expr = expr.BitAnd(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:339
		{
			yyVAL.expr = expr.ShiftLeftLogical(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:343
		{
			yyVAL.expr = expr.ShiftRightLogical(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:347
		{
			yyVAL.expr = expr.ShiftRightArithmetic(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:351
		{
			yyVAL.expr = expr.Add(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:355
		{
			yyVAL.expr = expr.Sub(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:359
		{
			yyVAL.expr = expr.Mul(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:363
		{
			yyVAL.expr = expr.Div(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:367
		{
			yyVAL.expr = expr.Mod(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:371
		{
			yyVAL.expr = expr.Call("CONCAT", yyDollar[1].expr, yyDollar[3].expr)
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:375
		{
			yyVAL.expr = expr.Append(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:379
		{
			yyVAL.expr = expr.Neg(yyDollar[2].expr)
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:383
		{
			yyVAL.expr = expr.Compare(expr.Ilike, yyDollar[1].expr, expr.String(yyDollar[3].str))
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:387
		{
			yyVAL.expr = expr.Compare(expr.Like, yyDollar[1].expr, expr.String(yyDollar[3].str))
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:391
		{
			yyVAL.expr = expr.Compare(expr.Equals, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:395
		{
			yyVAL.expr = expr.Compare(expr.NotEquals, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:399
		{
			yyVAL.expr = expr.Compare(expr.Less, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:403
		{
			yyVAL.expr = expr.Compare(expr.LessEquals, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:407
		{
			yyVAL.expr = expr.Compare(expr.Greater, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:411
		{
			yyVAL.expr = expr.Compare(expr.GreaterEquals, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 79:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:415
		{
			yyVAL.expr = expr.Between(yyDollar[1].expr, yyDollar[3].expr, yyDollar[5].expr)
		}
	case 80:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:419
		{
			yyVAL.expr = &expr.Not{Expr: expr.Compare(expr.Like, yyDollar[1].expr, expr.String(yyDollar[4].str))}
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:423
		{
			yyVAL.expr = &expr.Not{Expr: yyDollar[2].expr}
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:427
		{
			yyVAL.expr = expr.BitNot(yyDollar[2].expr)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:431
		{
			yyVAL.expr = expr.And(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:435
		{
			yyVAL.expr = expr.Or(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:439
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNull, Expr: yyDollar[1].expr}
		}
	case 86:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:443
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNotNull, Expr: yyDollar[1].expr}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:447
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsMissing, Expr: yyDollar[1].expr}
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:451
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNotMissing, Expr: yyDollar[1].expr}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:455
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsTrue, Expr: yyDollar[1].expr}
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:459
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNotTrue, Expr: yyDollar[1].expr}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:463
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsFalse, Expr: yyDollar[1].expr}
		}
	case 92:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:467
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNotFalse, Expr: yyDollar[1].expr}
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:473
		{
			yyVAL.bindings = []expr.Binding{yyDollar[1].bind}
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:474
		{
			yyVAL.bindings = append(yyDollar[1].bindings, yyDollar[3].bind)
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:478
		{
			yyVAL.values = []expr.Node{yyDollar[1].expr}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:479
		{
			yyVAL.values = []expr.Node{expr.Star{}}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:480
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].expr)
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:483
		{
			yyVAL.jk = expr.InnerJoin
		}
	case 99:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:484
		{
			yyVAL.jk = expr.InnerJoin
		}
	case 100:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:485
		{
			yyVAL.jk = expr.LeftJoin
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:486
		{
			yyVAL.jk = expr.LeftJoin
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:487
		{
			yyVAL.jk = expr.RightJoin
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:488
		{
			yyVAL.jk = expr.RightJoin
		}
	case 104:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:489
		{
			yyVAL.jk = expr.FullJoin
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:494
		{
			yyVAL.from = yyDollar[1].from
		}
	case 108:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:495
		{
			yyVAL.from = nil
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:502
		{
			yyVAL.from = &expr.Table{Binding: yyDollar[2].bind}
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:503
		{
			yyVAL.from = &expr.Join{Kind: expr.CrossJoin, Left: yyDollar[1].from, Right: yyDollar[3].bind}
		}
	case 111:
		yyDollar = yyS[yypt-7 : yypt+1]
//line partiql.y:505
		{
			yyVAL.from = &expr.Join{Kind: yyDollar[2].jk, Left: yyDollar[1].from, Right: yyDollar[3].bind, On: &expr.OnEquals{Left: yyDollar[5].expr, Right: yyDollar[7].expr}}
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:508
		{
			var idxerr error
			yyVAL.integer, idxerr = toint(yyDollar[1].expr)
			if idxerr != nil {
				yylex.Error(idxerr.Error())
			}
		}
	case 113:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:511
		{
			yyVAL.pc = nil
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:512
		{
			yyVAL.pc = &expr.Dot{Field: yyDollar[2].str, Rest: yyDollar[3].pc}
		}
	case 115:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:513
		{
			yyVAL.pc = &expr.LiteralIndex{Field: yyDollar[2].integer, Rest: yyDollar[4].pc}
		}
	case 116:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:514
		{
			yyVAL.pc = &expr.Dot{Field: yyDollar[2].str, Rest: yyDollar[4].pc}
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:523
		{
			yyVAL.str = yyDollar[1].str
		}
	case 118:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:526
		{
			yyVAL.expr = nil
		}
	case 119:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:527
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 120:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:530
		{
			yyVAL.limbs = []expr.CaseLimb{{When: yyDollar[2].expr, Then: yyDollar[4].expr}}
		}
	case 121:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:531
		{
			yyVAL.limbs = append(yyDollar[1].limbs, expr.CaseLimb{When: yyDollar[3].expr, Then: yyDollar[5].expr})
		}
	case 122:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:534
		{
			yyVAL.expr = nil
		}
	case 123:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:535
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 124:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:538
		{
			yyVAL.expr = nil
		}
	case 125:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:539
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 126:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:542
		{
			yyVAL.bindings = nil
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:543
		{
			yyVAL.bindings = yyDollar[3].bindings
		}
	case 128:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:547
		{
			yyVAL.yesno = false
		}
	case 129:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:548
		{
			yyVAL.yesno = false
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:549
		{
			yyVAL.yesno = true
		}
	case 131:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:553
		{
			yyVAL.yesno = false
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:554
		{
			yyVAL.yesno = false
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:555
		{
			yyVAL.yesno = true
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:559
		{
			yyVAL.order = expr.Order{Column: yyDollar[1].expr, Desc: yyDollar[2].yesno, NullsLast: yyDollar[3].yesno}
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:562
		{
			yyVAL.orders = append(yyDollar[1].orders, yyDollar[3].order)
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:563
		{
			yyVAL.orders = []expr.Order{yyDollar[1].order}
		}
	case 137:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:566
		{
			yyVAL.orders = nil
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:567
		{
			yyVAL.orders = yyDollar[3].orders
		}
	case 139:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:570
		{
			yyVAL.exprint = nil
		}
	case 140:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:571
		{
			n := expr.Integer(yyDollar[2].integer)
			yyVAL.exprint = &n
		}
	case 141:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:574
		{
			yyVAL.exprint = nil
		}
	case 142:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:575
		{
			n := expr.Integer(yyDollar[2].integer)
			yyVAL.exprint = &n
		}
	}
	goto yystack /* stack new state and value */
}
