// Code generated by goyacc partiql.y. DO NOT EDIT.

//line partiql.y:15
// Copyright (C) 2022 Sneller, Inc.
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package partiql

import (
	__yyfmt__ "fmt"

	"github.com/SnellerInc/sneller/expr"
) //line partiql.y:29

//line partiql.y:36
type yySymType struct {
	yys      int
	bytes    []byte
	str      string
	yesno    bool
	integer  int
	exprint  *expr.Integer
	expr     expr.Node
	pc       expr.PathComponent
	order    expr.Order
	sel      *expr.Select
	wind     *expr.Window
	bind     expr.Binding
	jk       expr.JoinKind
	from     expr.From
	with     []expr.CTE
	bindings []expr.Binding
	limbs    []expr.CaseLimb
	values   []expr.Node
	orders   []expr.Order
}

const ERROR = 57346
const EOF = 57347
const UNION = 57348
const SELECT = 57349
const FROM = 57350
const WHERE = 57351
const GROUP = 57352
const ORDER = 57353
const BY = 57354
const HAVING = 57355
const LIMIT = 57356
const OFFSET = 57357
const WITH = 57358
const INTO = 57359
const DISTINCT = 57360
const ALL = 57361
const AS = 57362
const EXISTS = 57363
const NULLS = 57364
const FIRST = 57365
const LAST = 57366
const ASC = 57367
const DESC = 57368
const UNPIVOT = 57369
const AT = 57370
const PARTITION = 57371
const VALUE = 57372
const COALESCE = 57373
const NULLIF = 57374
const EXTRACT = 57375
const DATE_TRUNC = 57376
const CAST = 57377
const UTCNOW = 57378
const DATE_ADD = 57379
const DATE_DIFF = 57380
const EARLIEST = 57381
const LATEST = 57382
const JOIN = 57383
const LEFT = 57384
const RIGHT = 57385
const CROSS = 57386
const INNER = 57387
const OUTER = 57388
const FULL = 57389
const ON = 57390
const AGGREGATE = 57391
const ID = 57392
const NULL = 57393
const TRUE = 57394
const FALSE = 57395
const MISSING = 57396
const OR = 57397
const AND = 57398
const NOT = 57399
const BETWEEN = 57400
const CASE = 57401
const WHEN = 57402
const THEN = 57403
const ELSE = 57404
const END = 57405
const TO = 57406
const EQ = 57407
const NE = 57408
const LT = 57409
const LE = 57410
const GT = 57411
const GE = 57412
const SIMILAR = 57413
const REGEXP_MATCH_CI = 57414
const ILIKE = 57415
const LIKE = 57416
const IN = 57417
const IS = 57418
const OVER = 57419
const FILTER = 57420
const SHIFT_LEFT_LOGICAL = 57421
const SHIFT_RIGHT_ARITHMETIC = 57422
const SHIFT_RIGHT_LOGICAL = 57423
const CONCAT = 57424
const APPEND = 57425
const NEGATION_PRECEDENCE = 57426
const NUMBER = 57427
const ION = 57428
const STRING = 57429

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ERROR",
	"EOF",
	"UNION",
	"SELECT",
	"FROM",
	"WHERE",
	"GROUP",
	"ORDER",
	"BY",
	"HAVING",
	"LIMIT",
	"OFFSET",
	"WITH",
	"INTO",
	"DISTINCT",
	"ALL",
	"AS",
	"EXISTS",
	"NULLS",
	"FIRST",
	"LAST",
	"ASC",
	"DESC",
	"UNPIVOT",
	"AT",
	"PARTITION",
	"VALUE",
	"COALESCE",
	"NULLIF",
	"EXTRACT",
	"DATE_TRUNC",
	"CAST",
	"UTCNOW",
	"DATE_ADD",
	"DATE_DIFF",
	"EARLIEST",
	"LATEST",
	"JOIN",
	"LEFT",
	"RIGHT",
	"CROSS",
	"INNER",
	"OUTER",
	"FULL",
	"ON",
	"AGGREGATE",
	"ID",
	"'('",
	"','",
	"')'",
	"'['",
	"']'",
	"'{'",
	"'}'",
	"NULL",
	"TRUE",
	"FALSE",
	"MISSING",
	"OR",
	"AND",
	"'!'",
	"'~'",
	"NOT",
	"BETWEEN",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"TO",
	"EQ",
	"NE",
	"LT",
	"LE",
	"GT",
	"GE",
	"SIMILAR",
	"REGEXP_MATCH_CI",
	"ILIKE",
	"LIKE",
	"IN",
	"IS",
	"OVER",
	"FILTER",
	"'|'",
	"'^'",
	"'&'",
	"SHIFT_LEFT_LOGICAL",
	"SHIFT_RIGHT_ARITHMETIC",
	"SHIFT_RIGHT_LOGICAL",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"CONCAT",
	"APPEND",
	"NEGATION_PRECEDENCE",
	"'.'",
	"NUMBER",
	"ION",
	"STRING",
	"':'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 336,
	62, 67,
	63, 67,
	65, 67,
	66, 67,
	67, 67,
	74, 67,
	75, 67,
	76, 67,
	77, 67,
	78, 67,
	79, 67,
	-2, 123,
}

const yyPrivate = 57344

const yyLast = 1648

var yyAct = [...]int16{
	15, 330, 334, 310, 186, 321, 256, 290, 173, 297,
	13, 203, 273, 122, 98, 113, 17, 9, 14, 196,
	271, 107, 64, 65, 66, 67, 68, 69, 70, 114,
	223, 103, 104, 105, 8, 37, 222, 220, 108, 111,
	219, 217, 44, 42, 43, 45, 59, 60, 61, 63,
	62, 64, 65, 66, 67, 68, 69, 70, 146, 129,
	130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
	140, 141, 125, 121, 145, 143, 142, 147, 148, 149,
	150, 151, 152, 187, 188, 159, 160, 41, 47, 46,
	172, 174, 176, 177, 274, 99, 101, 28, 101, 153,
	174, 168, 7, 298, 11, 69, 70, 221, 184, 144,
	230, 218, 89, 56, 66, 67, 68, 69, 70, 170,
	200, 171, 192, 194, 189, 193, 341, 191, 195, 174,
	245, 161, 164, 165, 163, 8, 188, 216, 118, 162,
	354, 39, 201, 214, 100, 53, 100, 244, 235, 269,
	215, 311, 118, 127, 60, 61, 63, 62, 64, 65,
	66, 67, 68, 69, 70, 254, 253, 228, 235, 242,
	302, 231, 232, 224, 226, 227, 225, 48, 268, 167,
	118, 61, 63, 62, 64, 65, 66, 67, 68, 69,
	70, 157, 235, 248, 235, 234, 255, 250, 185, 124,
	243, 246, 247, 229, 202, 258, 156, 158, 155, 154,
	249, 209, 211, 212, 208, 210, 190, 213, 116, 182,
	240, 54, 207, 239, 259, 260, 238, 6, 316, 299,
	128, 120, 126, 119, 276, 270, 277, 278, 102, 280,
	281, 282, 283, 53, 97, 96, 95, 94, 93, 92,
	91, 90, 87, 51, 293, 289, 53, 8, 279, 284,
	285, 286, 181, 180, 179, 178, 49, 265, 263, 295,
	294, 267, 266, 264, 262, 261, 300, 325, 34, 197,
	287, 352, 353, 349, 288, 296, 50, 198, 12, 10,
	4, 331, 312, 322, 314, 251, 252, 291, 307, 337,
	323, 292, 311, 313, 318, 319, 315, 257, 317, 204,
	241, 124, 109, 5, 320, 205, 118, 88, 326, 117,
	206, 333, 199, 112, 335, 336, 110, 332, 329, 123,
	166, 348, 342, 339, 3, 2, 340, 115, 174, 33,
	109, 35, 335, 106, 347, 346, 345, 169, 351, 350,
	52, 36, 1, 0, 29, 0, 0, 0, 0, 0,
	40, 0, 0, 0, 20, 21, 26, 25, 22, 27,
	23, 24, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 18, 8, 37, 308, 309, 38, 0, 39,
	0, 44, 42, 43, 45, 0, 0, 0, 32, 31,
	0, 19, 73, 75, 71, 72, 57, 86, 0, 0,
	58, 59, 60, 61, 63, 62, 64, 65, 66, 67,
	68, 69, 70, 0, 0, 0, 0, 0, 30, 175,
	0, 0, 0, 29, 0, 0, 41, 47, 46, 40,
	0, 0, 0, 20, 21, 26, 25, 22, 27, 23,
	24, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 18, 8, 37, 0, 183, 38, 0, 39, 0,
	44, 42, 43, 45, 0, 0, 0, 32, 31, 0,
	19, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 30, 175, 0,
	0, 0, 29, 0, 0, 41, 47, 46, 40, 0,
	0, 0, 20, 21, 26, 25, 22, 27, 23, 24,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	18, 8, 37, 0, 0, 38, 0, 39, 0, 44,
	42, 43, 45, 0, 0, 0, 32, 31, 0, 19,
	343, 344, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 30, 175, 0, 0,
	0, 0, 0, 0, 41, 47, 46, 85, 84, 0,
	74, 83, 82, 0, 0, 0, 0, 0, 0, 76,
	77, 78, 79, 80, 81, 73, 75, 71, 72, 57,
	86, 0, 0, 58, 59, 60, 61, 63, 62, 64,
	65, 66, 67, 68, 69, 70, 29, 0, 0, 0,
	0, 0, 40, 0, 0, 0, 20, 21, 26, 25,
	22, 27, 23, 24, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 18, 8, 37, 0, 0, 38,
	0, 39, 0, 44, 42, 43, 45, 0, 0, 0,
	32, 31, 0, 19, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 109, 0, 0, 0, 0, 0, 0, 0, 0,
	30, 16, 0, 0, 0, 29, 0, 0, 41, 47,
	46, 40, 0, 0, 0, 20, 21, 26, 25, 22,
	27, 23, 24, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 18, 8, 37, 0, 0, 38, 55,
	39, 0, 44, 42, 43, 45, 0, 0, 0, 32,
	31, 0, 19, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 30,
	0, 85, 84, 0, 74, 83, 82, 41, 47, 46,
	0, 0, 0, 76, 77, 78, 79, 80, 81, 73,
	75, 71, 72, 57, 86, 0, 0, 58, 59, 60,
	61, 63, 62, 64, 65, 66, 67, 68, 69, 70,
	29, 0, 0, 0, 0, 0, 40, 0, 0, 0,
	20, 21, 26, 25, 22, 27, 23, 24, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 18, 8,
	37, 0, 0, 38, 0, 39, 0, 44, 42, 43,
	45, 0, 0, 0, 32, 31, 0, 19, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 338, 0, 0, 0,
	0, 0, 0, 0, 30, 85, 84, 0, 74, 83,
	82, 0, 41, 47, 46, 0, 0, 76, 77, 78,
	79, 80, 81, 73, 75, 71, 72, 57, 86, 0,
	0, 58, 59, 60, 61, 63, 62, 64, 65, 66,
	67, 68, 69, 70, 328, 0, 0, 0, 0, 0,
	0, 0, 0, 85, 84, 0, 74, 83, 82, 0,
	0, 0, 0, 0, 0, 76, 77, 78, 79, 80,
	81, 73, 75, 71, 72, 57, 86, 0, 0, 58,
	59, 60, 61, 63, 62, 64, 65, 66, 67, 68,
	69, 70, 327, 0, 0, 0, 0, 0, 0, 0,
	0, 85, 84, 0, 74, 83, 82, 0, 0, 0,
	0, 0, 0, 76, 77, 78, 79, 80, 81, 73,
	75, 71, 72, 57, 86, 0, 0, 58, 59, 60,
	61, 63, 62, 64, 65, 66, 67, 68, 69, 70,
	306, 0, 0, 0, 0, 0, 0, 0, 0, 85,
	84, 0, 74, 83, 82, 0, 0, 0, 0, 0,
	0, 76, 77, 78, 79, 80, 81, 73, 75, 71,
	72, 57, 86, 0, 0, 58, 59, 60, 61, 63,
	62, 64, 65, 66, 67, 68, 69, 70, 305, 0,
	0, 0, 0, 0, 0, 0, 0, 85, 84, 0,
	74, 83, 82, 0, 0, 0, 0, 0, 0, 76,
	77, 78, 79, 80, 81, 73, 75, 71, 72, 57,
	86, 0, 0, 58, 59, 60, 61, 63, 62, 64,
	65, 66, 67, 68, 69, 70, 304, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 85, 84, 0, 74,
	83, 82, 0, 0, 0, 0, 0, 0, 76, 77,
	78, 79, 80, 81, 73, 75, 71, 72, 57, 86,
	0, 0, 58, 59, 60, 61, 63, 62, 64, 65,
	66, 67, 68, 69, 70, 303, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 85, 84, 0, 74, 83,
	82, 0, 0, 0, 0, 0, 0, 76, 77, 78,
	79, 80, 81, 73, 75, 71, 72, 57, 86, 0,
	0, 58, 59, 60, 61, 63, 62, 64, 65, 66,
	67, 68, 69, 70, 301, 0, 0, 0, 0, 0,
	0, 0, 0, 85, 84, 0, 74, 83, 82, 0,
	0, 0, 0, 0, 0, 76, 77, 78, 79, 80,
	81, 73, 75, 71, 72, 57, 86, 0, 0, 58,
	59, 60, 61, 63, 62, 64, 65, 66, 67, 68,
	69, 70, 85, 84, 0, 74, 83, 82, 0, 0,
	275, 0, 0, 0, 76, 77, 78, 79, 80, 81,
	73, 75, 71, 72, 57, 86, 0, 0, 58, 59,
	60, 61, 63, 62, 64, 65, 66, 67, 68, 69,
	70, 272, 0, 0, 0, 0, 0, 237, 0, 0,
	85, 84, 0, 74, 83, 82, 0, 0, 0, 0,
	0, 0, 76, 77, 78, 79, 80, 81, 73, 75,
	71, 72, 57, 86, 0, 0, 58, 59, 60, 61,
	63, 62, 64, 65, 66, 67, 68, 69, 70, 85,
	84, 0, 74, 83, 82, 0, 0, 0, 0, 0,
	0, 76, 77, 78, 79, 80, 81, 73, 75, 71,
	72, 57, 86, 0, 0, 58, 59, 60, 61, 63,
	62, 64, 65, 66, 67, 68, 69, 70, 236, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 85, 84,
	0, 74, 83, 82, 0, 0, 0, 0, 0, 0,
	76, 77, 78, 79, 80, 81, 73, 75, 71, 72,
	57, 86, 0, 0, 58, 59, 60, 61, 63, 62,
	64, 65, 66, 67, 68, 69, 70, 85, 84, 0,
	74, 83, 82, 0, 0, 233, 0, 0, 0, 76,
	77, 78, 79, 80, 81, 73, 75, 71, 72, 57,
	86, 0, 0, 58, 59, 60, 61, 63, 62, 64,
	65, 66, 67, 68, 69, 70, 85, 84, 0, 74,
	83, 82, 0, 0, 0, 0, 0, 0, 324, 77,
	78, 79, 80, 81, 73, 75, 71, 72, 57, 86,
	0, 0, 58, 59, 60, 61, 63, 62, 64, 65,
	66, 67, 68, 69, 70, 85, 84, 0, 74, 83,
	82, 0, 0, 0, 0, 0, 0, 76, 77, 78,
	79, 80, 81, 73, 75, 71, 72, 57, 86, 0,
	0, 58, 59, 60, 61, 63, 62, 64, 65, 66,
	67, 68, 69, 70, 84, 0, 74, 83, 82, 0,
	0, 0, 0, 0, 0, 76, 77, 78, 79, 80,
	81, 73, 75, 71, 72, 57, 86, 0, 0, 58,
	59, 60, 61, 63, 62, 64, 65, 66, 67, 68,
	69, 70, 74, 83, 82, 0, 0, 0, 0, 0,
	0, 76, 77, 78, 79, 80, 81, 73, 75, 71,
	72, 57, 86, 0, 0, 58, 59, 60, 61, 63,
	62, 64, 65, 66, 67, 68, 69, 70,
}

var yyPact = [...]int16{
	274, -1000, 306, 175, 207, 271, 207, 268, -1000, 615,
	218, 266, 202, 204, -1000, 729, -1000, -1000, 201, 43,
	200, 199, 198, 197, 196, 195, 194, 193, 44, 187,
	809, 809, 809, -1000, -1000, -1000, -1000, 694, 809, -76,
	85, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 182,
	180, 305, 303, 615, 207, 207, -1000, 179, 809, 809,
	809, 809, 809, 809, 809, 809, 809, 809, 809, 809,
	809, -29, -30, 36, -31, -47, 809, 809, 809, 809,
	809, 809, -16, 126, 809, 809, 73, 83, 50, 809,
	491, 809, 809, 215, 214, 213, 212, 166, -1000, 412,
	207, 33, 305, -1000, 1547, 1547, 163, -1000, 1473, 271,
	70, 1473, 71, -1000, -87, 259, -1000, -1000, 42, 809,
	305, 151, 300, 170, 615, -1000, -1000, -1000, 333, -43,
	64, 90, -72, -72, -72, 18, 18, 6, 6, 6,
	-1000, -1000, -1000, -1000, -64, -1000, -1000, 322, 322, 322,
	322, 322, 322, 48, -65, -68, 34, -69, -75, 1547,
	1511, -1000, 115, -1000, -1000, -1000, 809, 150, -1000, 38,
	809, 809, 1395, 142, 1473, -1000, 1356, 1307, 174, 171,
	168, 302, -1000, -1000, 116, 42, 92, 75, -1000, 148,
	-1000, 615, 809, -1000, -76, -1000, 809, 207, 207, 113,
	1473, 143, -1000, 297, 809, 615, 615, -1000, 234, -1000,
	233, 227, 226, 230, -1000, 125, 96, -1000, -16, -1000,
	-1000, -85, -1000, -1000, -1000, -1000, -1000, -1000, 1268, 7,
	-1000, 1220, 1473, 809, -1000, 809, 809, 208, 809, 809,
	809, 809, -1000, -1000, 42, 42, -1000, 191, 1473, -1000,
	1473, 252, 264, -1000, 809, -1000, 284, 289, 1473, -1000,
	206, -1000, -1000, -1000, 229, -1000, 228, -1000, -1000, -1000,
	-1000, -1000, 7, 17, 178, 809, 1473, 1473, 1181, 117,
	1133, 1084, 1035, 987, -1000, -1000, 300, 207, 207, 1473,
	291, 809, 615, 809, -1000, -1000, 17, -1000, 177, 299,
	1473, -1000, -1000, 809, 809, -1000, -1000, 297, -1000, -1000,
	279, 288, 1473, 93, 1434, -1000, 248, 809, 939, 891,
	284, 276, -19, 809, 809, 287, 843, -1000, -1000, 291,
	-1000, -19, -1000, 74, -1000, 535, 322, 491, -1000, 279,
	-1000, 809, 261, -1000, -1000, 140, 276, -1000, -1000, 258,
	87, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 352, 0, 351, 16, 177, 350, 11, 7, 347,
	343, 12, 341, 278, 339, 337, 335, 334, 14, 332,
	331, 330, 97, 4, 21, 6, 10, 18, 13, 329,
	8, 326, 323, 15, 322, 17, 2, 3, 321, 320,
	5, 1, 317, 9, 315,
}

var yyR1 = [...]int8{
	0, 1, 24, 6, 6, 16, 16, 17, 17, 27,
	27, 27, 27, 5, 3, 3, 3, 3, 3, 3,
	3, 3, 4, 4, 10, 10, 21, 21, 35, 35,
	35, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 26, 26, 34, 34, 30, 30,
	30, 31, 31, 31, 32, 32, 32, 33, 43, 43,
	39, 39, 39, 39, 39, 39, 39, 44, 44, 28,
	28, 29, 29, 29, 23, 18, 18, 18, 18, 22,
	9, 9, 42, 42, 11, 11, 7, 7, 8, 8,
	25, 25, 20, 20, 20, 19, 19, 19, 36, 38,
	38, 37, 37, 40, 40, 41, 41, 12, 12, 12,
	15, 15, 13, 14,
}

var yyR2 = [...]int8{
	0, 12, 10, 2, 0, 1, 0, 6, 7, 3,
	2, 1, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 1, 1, 1, 0, 5, 1,
	0, 1, 7, 6, 4, 4, 6, 6, 8, 8,
	6, 6, 3, 3, 4, 5, 5, 4, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 3, 3, 4, 3, 3, 3, 3, 3,
	3, 3, 3, 5, 4, 4, 5, 4, 4, 2,
	2, 3, 3, 3, 4, 3, 4, 3, 4, 3,
	4, 1, 1, 1, 1, 3, 1, 3, 1, 1,
	3, 1, 3, 0, 1, 3, 0, 3, 7, 0,
	1, 2, 2, 3, 2, 3, 2, 1, 2, 1,
	0, 2, 3, 7, 1, 0, 3, 4, 4, 1,
	0, 2, 4, 5, 0, 5, 0, 2, 0, 2,
	0, 3, 0, 2, 2, 0, 1, 1, 3, 3,
	1, 0, 3, 0, 2, 0, 2, 4, 6, 6,
	1, 1, 3, 3,
}

var yyChk = [...]int16{
	-1000, -1, -16, -17, 16, 7, 52, -22, 50, -35,
	18, -22, 20, -26, -27, -2, 96, -4, 49, 68,
	31, 32, 35, 37, 38, 34, 33, 36, -22, 21,
	95, 66, 65, -14, -13, -12, -3, 51, 54, 56,
	27, 103, 59, 60, 58, 61, 105, 104, -5, 48,
	20, 51, -6, 52, 17, 20, -22, 84, 88, 89,
	90, 91, 93, 92, 94, 95, 96, 97, 98, 99,
	100, 82, 83, 80, 65, 81, 74, 75, 76, 77,
	78, 79, 67, 66, 63, 62, 85, 51, -42, 69,
	51, 51, 51, 51, 51, 51, 51, 51, -18, 51,
	102, 54, 51, -2, -2, -2, -10, -24, -2, 7,
	-31, -2, -32, -33, 105, -15, -5, -13, -22, 51,
	51, -24, -28, -29, 8, -27, -5, -22, 51, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, 105, 105, 73, 105, 105, -2, -2, -2,
	-2, -2, -2, -4, 83, 82, 80, 65, 81, -2,
	-2, 58, 66, 61, 59, 60, -21, 96, 18, -9,
	69, 71, -2, -30, -2, 96, -2, -2, 50, 50,
	50, 50, 53, 53, -30, -22, -23, 50, 103, -24,
	53, -35, 52, 55, 52, 57, 106, 20, 28, -34,
	-2, -24, 53, -7, 9, -44, -39, 52, 44, 41,
	45, 42, 43, 47, -27, -24, -30, 105, 63, 105,
	105, 73, 105, 105, 58, 61, 59, 60, -2, 53,
	72, -2, -2, 70, 53, 52, 52, 20, 52, 52,
	52, 8, 53, -18, 55, 55, 53, -26, -2, -33,
	-2, -22, -22, 53, 52, 53, -25, 10, -2, -27,
	-27, 41, 41, 41, 46, 41, 46, 41, 53, 53,
	-4, 105, 53, -11, 87, 70, -2, -2, -2, 50,
	-2, -2, -2, -2, -18, -18, -28, 28, 20, -2,
	-8, 13, 12, 48, 41, 41, -11, -43, 86, 51,
	-2, 53, 53, 52, 52, 53, 53, -7, -22, -22,
	-37, 11, -2, -26, -2, -43, 51, 9, -2, -2,
	-25, -40, 14, 12, 74, 29, -2, 53, 53, -8,
	-41, 15, -23, -38, -36, -2, -2, 12, 53, -37,
	-23, 52, -19, 25, 26, -30, -40, -36, -20, 22,
	-37, -41, 23, 24, 53,
}

var yyDef = [...]int16{
	6, -2, 0, 5, 0, 30, 0, 0, 129, 0,
	29, 0, 0, 4, 94, 11, 12, 31, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 125, 0,
	0, 0, 0, 91, 92, 93, 22, 0, 103, 106,
	0, 14, 15, 16, 17, 18, 19, 20, 21, 0,
	0, 0, 120, 0, 0, 0, 10, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 27, 130, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 13, 0,
	0, 0, 0, 61, 79, 80, 0, 24, 25, 30,
	0, 101, 0, 104, 0, 0, 160, 161, 125, 0,
	0, 0, 136, 119, 0, 95, 3, 9, 0, 48,
	49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
	59, 60, 62, 63, 0, 65, 66, 67, 68, 69,
	70, 71, 72, 0, 0, 0, 0, 0, 0, 81,
	82, 83, 0, 85, 87, 89, 0, 0, 26, 0,
	0, 0, 0, 0, 98, 99, 0, 0, 0, 0,
	0, 0, 42, 43, 0, 125, 0, 0, 124, 0,
	23, 0, 0, 163, 0, 162, 0, 0, 0, 0,
	96, 0, 7, 140, 0, 0, 0, 117, 0, 110,
	0, 0, 0, 0, 121, 0, 0, 64, 0, 74,
	75, 0, 77, 78, 84, 86, 88, 90, 0, 134,
	34, 0, 131, 0, 35, 0, 0, 0, 0, 0,
	0, 0, 44, 126, 125, 125, 47, 120, 102, 105,
	107, 157, 0, 28, 0, 8, 138, 0, 137, 122,
	0, 118, 111, 112, 0, 114, 0, 116, 45, 46,
	73, 76, 134, 109, 0, 0, 132, 100, 0, 0,
	0, 0, 0, 0, 127, 128, 136, 0, 0, 97,
	151, 0, 0, 0, 113, 115, 109, 33, 0, 0,
	133, 36, 37, 0, 0, 40, 41, 140, 158, 159,
	153, 0, 139, 141, 0, 32, 0, 0, 0, 0,
	138, 155, 0, 0, 0, 0, 0, 38, 39, 151,
	1, 0, 154, 152, 150, 145, -2, 0, 135, 153,
	156, 0, 142, 146, 147, 151, 155, 149, 148, 0,
	0, 2, 143, 144, 108,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 64, 3, 3, 3, 98, 90, 3,
	51, 53, 96, 94, 52, 95, 102, 97, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 106, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 54, 3, 55, 89, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 56, 88, 57, 65,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 58,
	59, 60, 61, 62, 63, 66, 67, 68, 69, 70,
	71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
	81, 82, 83, 84, 85, 86, 87, 91, 92, 93,
	99, 100, 101, 103, 104, 105,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-12 : yypt+1]
//line partiql.y:120
		{
			yylex.(*scanner).with = yyDollar[1].with
			yylex.(*scanner).into = yyDollar[5].expr
			distinct, distinctExpr := decodeDistinct(yyDollar[3].values)
			yylex.(*scanner).result = &expr.Select{Distinct: distinct, DistinctExpr: distinctExpr, Columns: yyDollar[4].bindings, From: yyDollar[6].from, Where: yyDollar[7].expr, GroupBy: yyDollar[8].bindings, Having: yyDollar[9].expr, OrderBy: yyDollar[10].orders, Limit: yyDollar[11].exprint, Offset: yyDollar[12].exprint}
		}
	case 2:
		yyDollar = yyS[yypt-10 : yypt+1]
//line partiql.y:129
		{
			distinct, distinctExpr := decodeDistinct(yyDollar[2].values)
			yyVAL.sel = &expr.Select{Distinct: distinct, DistinctExpr: distinctExpr, Columns: yyDollar[3].bindings, From: yyDollar[4].from, Where: yyDollar[5].expr, GroupBy: yyDollar[6].bindings, Having: yyDollar[7].expr, OrderBy: yyDollar[8].orders, Limit: yyDollar[9].exprint, Offset: yyDollar[10].exprint}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:135
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:135
		{
			yyVAL.expr = nil
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:138
		{
			yyVAL.with = yyDollar[1].with
		}
	case 6:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:138
		{
			yyVAL.with = nil
		}
	case 7:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:141
		{
			yyVAL.with = []expr.CTE{{Table: yyDollar[2].str, As: yyDollar[5].sel}}
		}
	case 8:
		yyDollar = yyS[yypt-7 : yypt+1]
//line partiql.y:142
		{
			yyVAL.with = append(yyDollar[1].with, expr.CTE{Table: yyDollar[3].str, As: yyDollar[6].sel})
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:148
		{
			yyVAL.bind = expr.Bind(yyDollar[1].expr, yyDollar[3].str)
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:149
		{
			yyVAL.bind = expr.Bind(yyDollar[1].expr, yyDollar[2].str)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:150
		{
			yyVAL.bind = expr.Bind(yyDollar[1].expr, "")
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:151
		{
			yyVAL.bind = expr.Bind(expr.Star{}, "")
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:154
		{
			yyVAL.expr = &expr.Path{First: yyDollar[1].str, Rest: yyDollar[2].pc}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:158
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:159
		{
			yyVAL.expr = expr.Bool(true)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:160
		{
			yyVAL.expr = expr.Bool(false)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:161
		{
			yyVAL.expr = expr.Null{}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:162
		{
			yyVAL.expr = expr.Missing{}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:163
		{
			yyVAL.expr = expr.String(yyDollar[1].str)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:164
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:165
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:177
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:178
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:181
		{
			yyVAL.expr = yyDollar[1].sel
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:182
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:185
		{
			yyVAL.yesno = true
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:185
		{
			yyVAL.yesno = false
		}
	case 28:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:188
		{
			yyVAL.values = yyDollar[4].values
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:189
		{
			yyVAL.values = []expr.Node{}
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:190
		{
			yyVAL.values = nil
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:196
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 32:
		yyDollar = yyS[yypt-7 : yypt+1]
//line partiql.y:200
		{
			agg, err := toAggregate(expr.AggregateOp(yyDollar[1].integer), yyDollar[4].expr, yyDollar[3].yesno, yyDollar[6].expr, yyDollar[7].wind)
			if err != nil {
				yylex.Error(__yyfmt__.Sprintf("%s", err))
			}
			yyVAL.expr = agg
		}
	case 33:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:208
		{
			distinct := false
			agg, err := toAggregate(expr.AggregateOp(yyDollar[1].integer), expr.Star{}, distinct, yyDollar[5].expr, yyDollar[6].wind)
			if err != nil {
				yylex.Error(__yyfmt__.Sprintf("%s", err))
			}
			yyVAL.expr = agg
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:217
		{
			yyVAL.expr = &expr.Case{Limbs: yyDollar[2].limbs, Else: yyDollar[3].expr}
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:221
		{
			yyVAL.expr = expr.Coalesce(yyDollar[3].values)
		}
	case 36:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:225
		{
			yyVAL.expr = expr.NullIf(yyDollar[3].expr, yyDollar[5].expr)
		}
	case 37:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:229
		{
			nod, ok := buildCast(yyDollar[3].expr, yyDollar[5].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad CAST type %q", yyDollar[5].str))
				return 1
			}
			yyVAL.expr = nod
		}
	case 38:
		yyDollar = yyS[yypt-8 : yypt+1]
//line partiql.y:238
		{
			part, ok := timePart(yyDollar[3].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad DATE_ADD part %q", yyDollar[3].str))
			}
			yyVAL.expr = expr.DateAdd(part, yyDollar[5].expr, yyDollar[7].expr)
		}
	case 39:
		yyDollar = yyS[yypt-8 : yypt+1]
//line partiql.y:246
		{
			part, ok := timePart(yyDollar[3].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad DATE_DIFF part %q", yyDollar[3].str))
			}
			yyVAL.expr = expr.DateDiff(part, yyDollar[5].expr, yyDollar[7].expr)
		}
	case 40:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:254
		{
			part, ok := timePart(yyDollar[3].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad DATE_TRUNC part %q", yyDollar[3].str))
			}
			yyVAL.expr = expr.DateTrunc(part, yyDollar[5].expr)
		}
	case 41:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:262
		{
			part, ok := timePart(yyDollar[3].str)
			if !ok {
				yylex.Error(__yyfmt__.Sprintf("bad EXTRACT part %q", yyDollar[3].str))
			}
			yyVAL.expr = expr.DateExtract(part, yyDollar[5].expr)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:270
		{
			yyVAL.expr = yylex.(*scanner).utcnow()
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:274
		{
			op := expr.Call(yyDollar[1].str)
			if op.Private() {
				yylex.Error(__yyfmt__.Sprintf("cannot use reserved builtin %q", yyDollar[1].str))
			}
			yyVAL.expr = op
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:282
		{
			op := expr.Call(yyDollar[1].str, yyDollar[3].values...)
			if op.Private() {
				yylex.Error(__yyfmt__.Sprintf("cannot use reserved builtin %q", yyDollar[1].str))
			}
			yyVAL.expr = op
		}
	case 45:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:290
		{
			yyVAL.expr = expr.CallOp(expr.InSubquery, yyDollar[1].expr, yyDollar[4].sel)
		}
	case 46:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:294
		{
			yyVAL.expr = expr.In(yyDollar[1].expr, yyDollar[4].values...)
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:298
		{
			yyVAL.expr = exists(yyDollar[3].sel)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:302
		{
			yyVAL.expr = expr.BitOr(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:306
		{
			yyVAL.expr = expr.BitXor(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:310
		{
			yyVAL.expr = expr.BitAnd(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:314
		{
			yyVAL.expr = expr.ShiftLeftLogical(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:318
		{
			yyVAL.expr = expr.ShiftRightLogical(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:322
		{
			yyVAL.expr = expr.ShiftRightArithmetic(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:326
		{
			yyVAL.expr = expr.Add(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:330
		{
			yyVAL.expr = expr.Sub(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:334
		{
			yyVAL.expr = expr.Mul(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:338
		{
			yyVAL.expr = expr.Div(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:342
		{
			yyVAL.expr = expr.Mod(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:346
		{
			yyVAL.expr = expr.Call("CONCAT", yyDollar[1].expr, yyDollar[3].expr)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:350
		{
			yyVAL.expr = expr.Append(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:354
		{
			yyVAL.expr = expr.Neg(yyDollar[2].expr)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:358
		{
			yyVAL.expr = expr.Compare(expr.Ilike, yyDollar[1].expr, expr.String(yyDollar[3].str))
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:362
		{
			yyVAL.expr = expr.Compare(expr.Like, yyDollar[1].expr, expr.String(yyDollar[3].str))
		}
	case 64:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:366
		{
			yyVAL.expr = expr.Compare(expr.SimilarTo, yyDollar[1].expr, expr.String(yyDollar[4].str))
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:370
		{
			yyVAL.expr = expr.Compare(expr.RegexpMatch, yyDollar[1].expr, expr.String(yyDollar[3].str))
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:374
		{
			yyVAL.expr = expr.Compare(expr.RegexpMatchCi, yyDollar[1].expr, expr.String(yyDollar[3].str))
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:378
		{
			yyVAL.expr = expr.Compare(expr.Equals, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:382
		{
			yyVAL.expr = expr.Compare(expr.NotEquals, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:386
		{
			yyVAL.expr = expr.Compare(expr.Less, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:390
		{
			yyVAL.expr = expr.Compare(expr.LessEquals, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:394
		{
			yyVAL.expr = expr.Compare(expr.Greater, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:398
		{
			yyVAL.expr = expr.Compare(expr.GreaterEquals, yyDollar[1].expr, yyDollar[3].expr)
		}
	case 73:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:402
		{
			yyVAL.expr = expr.Between(yyDollar[1].expr, yyDollar[3].expr, yyDollar[5].expr)
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:406
		{
			yyVAL.expr = &expr.Not{Expr: expr.Compare(expr.Like, yyDollar[1].expr, expr.String(yyDollar[4].str))}
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:410
		{
			yyVAL.expr = &expr.Not{Expr: expr.Compare(expr.Ilike, yyDollar[1].expr, expr.String(yyDollar[4].str))}
		}
	case 76:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:414
		{
			yyVAL.expr = &expr.Not{Expr: expr.Compare(expr.SimilarTo, yyDollar[1].expr, expr.String(yyDollar[5].str))}
		}
	case 77:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:418
		{
			yyVAL.expr = &expr.Not{Expr: expr.Compare(expr.RegexpMatch, yyDollar[1].expr, expr.String(yyDollar[4].str))}
		}
	case 78:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:422
		{
			yyVAL.expr = &expr.Not{Expr: expr.Compare(expr.RegexpMatchCi, yyDollar[1].expr, expr.String(yyDollar[4].str))}
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:426
		{
			yyVAL.expr = &expr.Not{Expr: yyDollar[2].expr}
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:430
		{
			yyVAL.expr = expr.BitNot(yyDollar[2].expr)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:434
		{
			yyVAL.expr = expr.And(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:438
		{
			yyVAL.expr = expr.Or(yyDollar[1].expr, yyDollar[3].expr)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:442
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNull, Expr: yyDollar[1].expr}
		}
	case 84:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:446
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNotNull, Expr: yyDollar[1].expr}
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:450
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsMissing, Expr: yyDollar[1].expr}
		}
	case 86:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:454
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNotMissing, Expr: yyDollar[1].expr}
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:458
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsTrue, Expr: yyDollar[1].expr}
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:462
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNotTrue, Expr: yyDollar[1].expr}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:466
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsFalse, Expr: yyDollar[1].expr}
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:470
		{
			yyVAL.expr = &expr.IsKey{Key: expr.IsNotFalse, Expr: yyDollar[1].expr}
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:475
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:480
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:485
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:491
		{
			yyVAL.bindings = []expr.Binding{yyDollar[1].bind}
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:492
		{
			yyVAL.bindings = append(yyDollar[1].bindings, yyDollar[3].bind)
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:496
		{
			yyVAL.values = []expr.Node{yyDollar[1].expr}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:497
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].expr)
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:501
		{
			yyVAL.values = []expr.Node{yyDollar[1].expr}
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:502
		{
			yyVAL.values = []expr.Node{expr.Star{}}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:503
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].expr)
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:507
		{
			yyVAL.values = []expr.Node{yyDollar[1].expr}
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:508
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].expr)
		}
	case 103:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:509
		{
			yyVAL.values = nil
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:513
		{
			yyVAL.values = yyDollar[1].values
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:514
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].values...)
		}
	case 106:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:515
		{
			yyVAL.values = nil
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:519
		{
			yyVAL.values = []expr.Node{expr.String(yyDollar[1].str), yyDollar[3].expr}
		}
	case 108:
		yyDollar = yyS[yypt-7 : yypt+1]
//line partiql.y:523
		{
			yyVAL.wind = &expr.Window{PartitionBy: yyDollar[5].values, OrderBy: yyDollar[6].orders}
		}
	case 109:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:526
		{
			yyVAL.wind = nil
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:529
		{
			yyVAL.jk = expr.InnerJoin
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:530
		{
			yyVAL.jk = expr.InnerJoin
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:531
		{
			yyVAL.jk = expr.LeftJoin
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:532
		{
			yyVAL.jk = expr.LeftJoin
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:533
		{
			yyVAL.jk = expr.RightJoin
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:534
		{
			yyVAL.jk = expr.RightJoin
		}
	case 116:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:535
		{
			yyVAL.jk = expr.FullJoin
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:540
		{
			yyVAL.from = yyDollar[1].from
		}
	case 120:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:541
		{
			yyVAL.from = nil
		}
	case 121:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:548
		{
			yyVAL.from = &expr.Table{Binding: yyDollar[2].bind}
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:549
		{
			yyVAL.from = &expr.Join{Kind: expr.CrossJoin, Left: yyDollar[1].from, Right: yyDollar[3].bind}
		}
	case 123:
		yyDollar = yyS[yypt-7 : yypt+1]
//line partiql.y:551
		{
			yyVAL.from = &expr.Join{Kind: yyDollar[2].jk, Left: yyDollar[1].from, Right: yyDollar[3].bind, On: &expr.OnEquals{Left: yyDollar[5].expr, Right: yyDollar[7].expr}}
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:554
		{
			var idxerr error
			yyVAL.integer, idxerr = toint(yyDollar[1].expr)
			if idxerr != nil {
				yylex.Error(idxerr.Error())
			}
		}
	case 125:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:557
		{
			yyVAL.pc = nil
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:558
		{
			yyVAL.pc = &expr.Dot{Field: yyDollar[2].str, Rest: yyDollar[3].pc}
		}
	case 127:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:559
		{
			yyVAL.pc = &expr.LiteralIndex{Field: yyDollar[2].integer, Rest: yyDollar[4].pc}
		}
	case 128:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:560
		{
			yyVAL.pc = &expr.Dot{Field: yyDollar[2].str, Rest: yyDollar[4].pc}
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:569
		{
			yyVAL.str = yyDollar[1].str
		}
	case 130:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:572
		{
			yyVAL.expr = nil
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:573
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 132:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:576
		{
			yyVAL.limbs = []expr.CaseLimb{{When: yyDollar[2].expr, Then: yyDollar[4].expr}}
		}
	case 133:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:577
		{
			yyVAL.limbs = append(yyDollar[1].limbs, expr.CaseLimb{When: yyDollar[3].expr, Then: yyDollar[5].expr})
		}
	case 134:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:580
		{
			yyVAL.expr = nil
		}
	case 135:
		yyDollar = yyS[yypt-5 : yypt+1]
//line partiql.y:581
		{
			yyVAL.expr = yyDollar[4].expr
		}
	case 136:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:584
		{
			yyVAL.expr = nil
		}
	case 137:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:585
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 138:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:588
		{
			yyVAL.expr = nil
		}
	case 139:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:589
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 140:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:592
		{
			yyVAL.bindings = nil
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:593
		{
			yyVAL.bindings = yyDollar[3].bindings
		}
	case 142:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:597
		{
			yyVAL.yesno = false
		}
	case 143:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:598
		{
			yyVAL.yesno = false
		}
	case 144:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:599
		{
			yyVAL.yesno = true
		}
	case 145:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:603
		{
			yyVAL.yesno = false
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:604
		{
			yyVAL.yesno = false
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:605
		{
			yyVAL.yesno = true
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:609
		{
			yyVAL.order = expr.Order{Column: yyDollar[1].expr, Desc: yyDollar[2].yesno, NullsLast: yyDollar[3].yesno}
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:612
		{
			yyVAL.orders = append(yyDollar[1].orders, yyDollar[3].order)
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:613
		{
			yyVAL.orders = []expr.Order{yyDollar[1].order}
		}
	case 151:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:616
		{
			yyVAL.orders = nil
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:617
		{
			yyVAL.orders = yyDollar[3].orders
		}
	case 153:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:620
		{
			yyVAL.exprint = nil
		}
	case 154:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:621
		{
			n := expr.Integer(yyDollar[2].integer)
			yyVAL.exprint = &n
		}
	case 155:
		yyDollar = yyS[yypt-0 : yypt+1]
//line partiql.y:624
		{
			yyVAL.exprint = nil
		}
	case 156:
		yyDollar = yyS[yypt-2 : yypt+1]
//line partiql.y:625
		{
			n := expr.Integer(yyDollar[2].integer)
			yyVAL.exprint = &n
		}
	case 157:
		yyDollar = yyS[yypt-4 : yypt+1]
//line partiql.y:628
		{
			yyVAL.expr = &expr.Unpivot{TupleRef: yyDollar[2].expr, As: yyDollar[4].str, At: ""}
		}
	case 158:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:629
		{
			yyVAL.expr = &expr.Unpivot{TupleRef: yyDollar[2].expr, As: yyDollar[4].str, At: yyDollar[6].str}
		}
	case 159:
		yyDollar = yyS[yypt-6 : yypt+1]
//line partiql.y:630
		{
			yyVAL.expr = &expr.Unpivot{TupleRef: yyDollar[2].expr, As: yyDollar[6].str, At: yyDollar[4].str}
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:633
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line partiql.y:634
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:637
		{
			yyVAL.expr = expr.Call("MAKE_STRUCT", yyDollar[2].values...)
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
//line partiql.y:640
		{
			yyVAL.expr = expr.Call("MAKE_LIST", yyDollar[2].values...)
		}
	}
	goto yystack /* stack new state and value */
}
